// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file product/v1/brand.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PaginationRequest, PaginationResponse } from "../../common/pagination_pb";
import { file_common_pagination } from "../../common/pagination_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file product/v1/brand.proto.
 */
export const file_product_v1_brand: GenFile = /*@__PURE__*/
  fileDesc("ChZwcm9kdWN0L3YxL2JyYW5kLnByb3RvEgpwcm9kdWN0LnYxIk8KC0JyYW5kRW50aXR5EgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSEQoJcmVzb3VyY2VzGAQgAygJIh0KD0dldEJyYW5kUmVxdWVzdBIKCgJpZBgBIAEoAyI5ChBHZXRCcmFuZFJlc3BvbnNlEiUKBGRhdGEYASABKAsyFy5wcm9kdWN0LnYxLkJyYW5kRW50aXR5IogBChFMaXN0QnJhbmRzUmVxdWVzdBItCgpwYWdpbmF0aW9uGAEgASgLMhkuY29tbW9uLlBhZ2luYXRpb25SZXF1ZXN0EhEKBG5hbWUYAiABKAlIAIgBARIYCgtkZXNjcmlwdGlvbhgDIAEoCUgBiAEBQgcKBV9uYW1lQg4KDF9kZXNjcmlwdGlvbiJrChJMaXN0QnJhbmRzUmVzcG9uc2USJQoEZGF0YRgBIAMoCzIXLnByb2R1Y3QudjEuQnJhbmRFbnRpdHkSLgoKcGFnaW5hdGlvbhgCIAEoCzIaLmNvbW1vbi5QYWdpbmF0aW9uUmVzcG9uc2UiSgoSQ3JlYXRlQnJhbmRSZXF1ZXN0EgwKBG5hbWUYASABKAkSEwoLZGVzY3JpcHRpb24YAiABKAkSEQoJcmVzb3VyY2VzGAMgAygJIjwKE0NyZWF0ZUJyYW5kUmVzcG9uc2USJQoEZGF0YRgBIAEoCzIXLnByb2R1Y3QudjEuQnJhbmRFbnRpdHkieQoSVXBkYXRlQnJhbmRSZXF1ZXN0EgoKAmlkGAEgASgDEhEKBG5hbWUYAiABKAlIAIgBARIYCgtkZXNjcmlwdGlvbhgDIAEoCUgBiAEBEhEKCXJlc291cmNlcxgEIAMoCUIHCgVfbmFtZUIOCgxfZGVzY3JpcHRpb24iFQoTVXBkYXRlQnJhbmRSZXNwb25zZSIgChJEZWxldGVCcmFuZFJlcXVlc3QSCgoCaWQYASABKAMiFQoTRGVsZXRlQnJhbmRSZXNwb25zZUKtAQoOY29tLnByb2R1Y3QudjFCCkJyYW5kUHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9wcm9kdWN0L3YxO3Byb2R1Y3R2MaICA1BYWKoCClByb2R1Y3QuVjHKAgpQcm9kdWN0XFYx4gIWUHJvZHVjdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2R1Y3Q6OlYxYgZwcm90bzM", [file_common_pagination]);

/**
 * BRAND ENTITY
 *
 * @generated from message product.v1.BrandEntity
 */
export type BrandEntity = Message<"product.v1.BrandEntity"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: repeated string resources = 4;
   */
  resources: string[];
};

/**
 * Describes the message product.v1.BrandEntity.
 * Use `create(BrandEntitySchema)` to create a new message.
 */
export const BrandEntitySchema: GenMessage<BrandEntity> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 0);

/**
 * @generated from message product.v1.GetBrandRequest
 */
export type GetBrandRequest = Message<"product.v1.GetBrandRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message product.v1.GetBrandRequest.
 * Use `create(GetBrandRequestSchema)` to create a new message.
 */
export const GetBrandRequestSchema: GenMessage<GetBrandRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 1);

/**
 * @generated from message product.v1.GetBrandResponse
 */
export type GetBrandResponse = Message<"product.v1.GetBrandResponse"> & {
  /**
   * @generated from field: product.v1.BrandEntity data = 1;
   */
  data?: BrandEntity;
};

/**
 * Describes the message product.v1.GetBrandResponse.
 * Use `create(GetBrandResponseSchema)` to create a new message.
 */
export const GetBrandResponseSchema: GenMessage<GetBrandResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 2);

/**
 * @generated from message product.v1.ListBrandsRequest
 */
export type ListBrandsRequest = Message<"product.v1.ListBrandsRequest"> & {
  /**
   * @generated from field: common.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message product.v1.ListBrandsRequest.
 * Use `create(ListBrandsRequestSchema)` to create a new message.
 */
export const ListBrandsRequestSchema: GenMessage<ListBrandsRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 3);

/**
 * @generated from message product.v1.ListBrandsResponse
 */
export type ListBrandsResponse = Message<"product.v1.ListBrandsResponse"> & {
  /**
   * @generated from field: repeated product.v1.BrandEntity data = 1;
   */
  data: BrandEntity[];

  /**
   * @generated from field: common.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message product.v1.ListBrandsResponse.
 * Use `create(ListBrandsResponseSchema)` to create a new message.
 */
export const ListBrandsResponseSchema: GenMessage<ListBrandsResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 4);

/**
 * @generated from message product.v1.CreateBrandRequest
 */
export type CreateBrandRequest = Message<"product.v1.CreateBrandRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: repeated string resources = 3;
   */
  resources: string[];
};

/**
 * Describes the message product.v1.CreateBrandRequest.
 * Use `create(CreateBrandRequestSchema)` to create a new message.
 */
export const CreateBrandRequestSchema: GenMessage<CreateBrandRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 5);

/**
 * @generated from message product.v1.CreateBrandResponse
 */
export type CreateBrandResponse = Message<"product.v1.CreateBrandResponse"> & {
  /**
   * @generated from field: product.v1.BrandEntity data = 1;
   */
  data?: BrandEntity;
};

/**
 * Describes the message product.v1.CreateBrandResponse.
 * Use `create(CreateBrandResponseSchema)` to create a new message.
 */
export const CreateBrandResponseSchema: GenMessage<CreateBrandResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 6);

/**
 * @generated from message product.v1.UpdateBrandRequest
 */
export type UpdateBrandRequest = Message<"product.v1.UpdateBrandRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: optional string name = 2;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;

  /**
   * @generated from field: repeated string resources = 4;
   */
  resources: string[];
};

/**
 * Describes the message product.v1.UpdateBrandRequest.
 * Use `create(UpdateBrandRequestSchema)` to create a new message.
 */
export const UpdateBrandRequestSchema: GenMessage<UpdateBrandRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 7);

/**
 * @generated from message product.v1.UpdateBrandResponse
 */
export type UpdateBrandResponse = Message<"product.v1.UpdateBrandResponse"> & {
};

/**
 * Describes the message product.v1.UpdateBrandResponse.
 * Use `create(UpdateBrandResponseSchema)` to create a new message.
 */
export const UpdateBrandResponseSchema: GenMessage<UpdateBrandResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 8);

/**
 * @generated from message product.v1.DeleteBrandRequest
 */
export type DeleteBrandRequest = Message<"product.v1.DeleteBrandRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message product.v1.DeleteBrandRequest.
 * Use `create(DeleteBrandRequestSchema)` to create a new message.
 */
export const DeleteBrandRequestSchema: GenMessage<DeleteBrandRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 9);

/**
 * @generated from message product.v1.DeleteBrandResponse
 */
export type DeleteBrandResponse = Message<"product.v1.DeleteBrandResponse"> & {
};

/**
 * Describes the message product.v1.DeleteBrandResponse.
 * Use `create(DeleteBrandResponseSchema)` to create a new message.
 */
export const DeleteBrandResponseSchema: GenMessage<DeleteBrandResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 10);

