// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/brand.proto (package product.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_common_pagination } from "../../common/pagination_pb";

/**
 * Describes the file product/v1/brand.proto.
 */
export const file_product_v1_brand = /*@__PURE__*/
  fileDesc("ChZwcm9kdWN0L3YxL2JyYW5kLnByb3RvEgpwcm9kdWN0LnYxIjwKC0JyYW5kRW50aXR5EgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkiHQoPR2V0QnJhbmRSZXF1ZXN0EgoKAmlkGAEgASgDIjkKEEdldEJyYW5kUmVzcG9uc2USJQoEZGF0YRgBIAEoCzIXLnByb2R1Y3QudjEuQnJhbmRFbnRpdHkiiAEKEUxpc3RCcmFuZHNSZXF1ZXN0Ei0KCnBhZ2luYXRpb24YASABKAsyGS5jb21tb24uUGFnaW5hdGlvblJlcXVlc3QSEQoEbmFtZRgCIAEoCUgAiAEBEhgKC2Rlc2NyaXB0aW9uGAMgASgJSAGIAQFCBwoFX25hbWVCDgoMX2Rlc2NyaXB0aW9uImsKEkxpc3RCcmFuZHNSZXNwb25zZRIlCgRkYXRhGAEgAygLMhcucHJvZHVjdC52MS5CcmFuZEVudGl0eRIuCgpwYWdpbmF0aW9uGAIgASgLMhouY29tbW9uLlBhZ2luYXRpb25SZXNwb25zZSI3ChJDcmVhdGVCcmFuZFJlcXVlc3QSDAoEbmFtZRgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCSI8ChNDcmVhdGVCcmFuZFJlc3BvbnNlEiUKBGRhdGEYASABKAsyFy5wcm9kdWN0LnYxLkJyYW5kRW50aXR5ImYKElVwZGF0ZUJyYW5kUmVxdWVzdBIKCgJpZBgBIAEoAxIRCgRuYW1lGAIgASgJSACIAQESGAoLZGVzY3JpcHRpb24YAyABKAlIAYgBAUIHCgVfbmFtZUIOCgxfZGVzY3JpcHRpb24iFQoTVXBkYXRlQnJhbmRSZXNwb25zZSIgChJEZWxldGVCcmFuZFJlcXVlc3QSCgoCaWQYASABKAMiFQoTRGVsZXRlQnJhbmRSZXNwb25zZUKtAQoOY29tLnByb2R1Y3QudjFCCkJyYW5kUHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9wcm9kdWN0L3YxO3Byb2R1Y3R2MaICA1BYWKoCClByb2R1Y3QuVjHKAgpQcm9kdWN0XFYx4gIWUHJvZHVjdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2R1Y3Q6OlYxYgZwcm90bzM", [file_common_pagination]);

/**
 * Describes the message product.v1.BrandEntity.
 * Use `create(BrandEntitySchema)` to create a new message.
 */
export const BrandEntitySchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 0);

/**
 * Describes the message product.v1.GetBrandRequest.
 * Use `create(GetBrandRequestSchema)` to create a new message.
 */
export const GetBrandRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 1);

/**
 * Describes the message product.v1.GetBrandResponse.
 * Use `create(GetBrandResponseSchema)` to create a new message.
 */
export const GetBrandResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 2);

/**
 * Describes the message product.v1.ListBrandsRequest.
 * Use `create(ListBrandsRequestSchema)` to create a new message.
 */
export const ListBrandsRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 3);

/**
 * Describes the message product.v1.ListBrandsResponse.
 * Use `create(ListBrandsResponseSchema)` to create a new message.
 */
export const ListBrandsResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 4);

/**
 * Describes the message product.v1.CreateBrandRequest.
 * Use `create(CreateBrandRequestSchema)` to create a new message.
 */
export const CreateBrandRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 5);

/**
 * Describes the message product.v1.CreateBrandResponse.
 * Use `create(CreateBrandResponseSchema)` to create a new message.
 */
export const CreateBrandResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 6);

/**
 * Describes the message product.v1.UpdateBrandRequest.
 * Use `create(UpdateBrandRequestSchema)` to create a new message.
 */
export const UpdateBrandRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 7);

/**
 * Describes the message product.v1.UpdateBrandResponse.
 * Use `create(UpdateBrandResponseSchema)` to create a new message.
 */
export const UpdateBrandResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 8);

/**
 * Describes the message product.v1.DeleteBrandRequest.
 * Use `create(DeleteBrandRequestSchema)` to create a new message.
 */
export const DeleteBrandRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 9);

/**
 * Describes the message product.v1.DeleteBrandResponse.
 * Use `create(DeleteBrandResponseSchema)` to create a new message.
 */
export const DeleteBrandResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_brand, 10);

