// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/product_model.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { PaginationRequest, PaginationResponse } from "../../common/pagination_pb";

/**
 * Describes the file product/v1/product_model.proto.
 */
export declare const file_product_v1_product_model: GenFile;

/**
 * @generated from message product.v1.ProductModelEntity
 */
export declare type ProductModelEntity = Message<"product.v1.ProductModelEntity"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 brand_id = 2;
   */
  brandId: bigint;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: int64 list_price = 5;
   */
  listPrice: bigint;

  /**
   * @generated from field: int64 date_manufactured = 6;
   */
  dateManufactured: bigint;

  /**
   * @generated from field: repeated string resources = 7;
   */
  resources: string[];

  /**
   * @generated from field: repeated string tags = 8;
   */
  tags: string[];
};

/**
 * Describes the message product.v1.ProductModelEntity.
 * Use `create(ProductModelEntitySchema)` to create a new message.
 */
export declare const ProductModelEntitySchema: GenMessage<ProductModelEntity>;

/**
 * @generated from message product.v1.GetProductModelRequest
 */
export declare type GetProductModelRequest = Message<"product.v1.GetProductModelRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message product.v1.GetProductModelRequest.
 * Use `create(GetProductModelRequestSchema)` to create a new message.
 */
export declare const GetProductModelRequestSchema: GenMessage<GetProductModelRequest>;

/**
 * @generated from message product.v1.GetProductModelResponse
 */
export declare type GetProductModelResponse = Message<"product.v1.GetProductModelResponse"> & {
  /**
   * @generated from field: product.v1.ProductModelEntity data = 1;
   */
  data?: ProductModelEntity;
};

/**
 * Describes the message product.v1.GetProductModelResponse.
 * Use `create(GetProductModelResponseSchema)` to create a new message.
 */
export declare const GetProductModelResponseSchema: GenMessage<GetProductModelResponse>;

/**
 * @generated from message product.v1.ListProductModelsRequest
 */
export declare type ListProductModelsRequest = Message<"product.v1.ListProductModelsRequest"> & {
  /**
   * @generated from field: common.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional int64 brand_id = 2;
   */
  brandId?: bigint;

  /**
   * @generated from field: optional string name = 3;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional int64 list_price_from = 5;
   */
  listPriceFrom?: bigint;

  /**
   * @generated from field: optional int64 list_price_to = 6;
   */
  listPriceTo?: bigint;

  /**
   * @generated from field: optional int64 date_manufactured_from = 7;
   */
  dateManufacturedFrom?: bigint;

  /**
   * @generated from field: optional int64 date_manufactured_to = 8;
   */
  dateManufacturedTo?: bigint;
};

/**
 * Describes the message product.v1.ListProductModelsRequest.
 * Use `create(ListProductModelsRequestSchema)` to create a new message.
 */
export declare const ListProductModelsRequestSchema: GenMessage<ListProductModelsRequest>;

/**
 * @generated from message product.v1.ListProductModelsResponse
 */
export declare type ListProductModelsResponse = Message<"product.v1.ListProductModelsResponse"> & {
  /**
   * @generated from field: repeated product.v1.ProductModelEntity data = 1;
   */
  data: ProductModelEntity[];

  /**
   * @generated from field: common.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message product.v1.ListProductModelsResponse.
 * Use `create(ListProductModelsResponseSchema)` to create a new message.
 */
export declare const ListProductModelsResponseSchema: GenMessage<ListProductModelsResponse>;

/**
 * @generated from message product.v1.CreateProductModelRequest
 */
export declare type CreateProductModelRequest = Message<"product.v1.CreateProductModelRequest"> & {
  /**
   * @generated from field: int64 brand_id = 1;
   */
  brandId: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: int64 list_price = 4;
   */
  listPrice: bigint;

  /**
   * @generated from field: int64 date_manufactured = 5;
   */
  dateManufactured: bigint;

  /**
   * @generated from field: repeated string resources = 6;
   */
  resources: string[];

  /**
   * @generated from field: repeated string tags = 7;
   */
  tags: string[];
};

/**
 * Describes the message product.v1.CreateProductModelRequest.
 * Use `create(CreateProductModelRequestSchema)` to create a new message.
 */
export declare const CreateProductModelRequestSchema: GenMessage<CreateProductModelRequest>;

/**
 * @generated from message product.v1.CreateProductModelResponse
 */
export declare type CreateProductModelResponse = Message<"product.v1.CreateProductModelResponse"> & {
  /**
   * @generated from field: product.v1.ProductModelEntity data = 1;
   */
  data?: ProductModelEntity;
};

/**
 * Describes the message product.v1.CreateProductModelResponse.
 * Use `create(CreateProductModelResponseSchema)` to create a new message.
 */
export declare const CreateProductModelResponseSchema: GenMessage<CreateProductModelResponse>;

/**
 * @generated from message product.v1.UpdateProductModelRequest
 */
export declare type UpdateProductModelRequest = Message<"product.v1.UpdateProductModelRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: optional int64 brand_id = 2;
   */
  brandId?: bigint;

  /**
   * @generated from field: optional string name = 3;
   */
  name?: string;

  /**
   * @generated from field: optional string description = 4;
   */
  description?: string;

  /**
   * @generated from field: optional int64 list_price = 5;
   */
  listPrice?: bigint;

  /**
   * @generated from field: optional int64 date_manufactured = 6;
   */
  dateManufactured?: bigint;
};

/**
 * Describes the message product.v1.UpdateProductModelRequest.
 * Use `create(UpdateProductModelRequestSchema)` to create a new message.
 */
export declare const UpdateProductModelRequestSchema: GenMessage<UpdateProductModelRequest>;

/**
 * @generated from message product.v1.UpdateProductModelResponse
 */
export declare type UpdateProductModelResponse = Message<"product.v1.UpdateProductModelResponse"> & {
};

/**
 * Describes the message product.v1.UpdateProductModelResponse.
 * Use `create(UpdateProductModelResponseSchema)` to create a new message.
 */
export declare const UpdateProductModelResponseSchema: GenMessage<UpdateProductModelResponse>;

/**
 * @generated from message product.v1.DeleteProductModelRequest
 */
export declare type DeleteProductModelRequest = Message<"product.v1.DeleteProductModelRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message product.v1.DeleteProductModelRequest.
 * Use `create(DeleteProductModelRequestSchema)` to create a new message.
 */
export declare const DeleteProductModelRequestSchema: GenMessage<DeleteProductModelRequest>;

/**
 * @generated from message product.v1.DeleteProductModelResponse
 */
export declare type DeleteProductModelResponse = Message<"product.v1.DeleteProductModelResponse"> & {
};

/**
 * Describes the message product.v1.DeleteProductModelResponse.
 * Use `create(DeleteProductModelResponseSchema)` to create a new message.
 */
export declare const DeleteProductModelResponseSchema: GenMessage<DeleteProductModelResponse>;

