// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/product.proto (package product.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_common_pagination } from "../../common/pagination_pb";

/**
 * Describes the file product/v1/product.proto.
 */
export const file_product_v1_product = /*@__PURE__*/
  fileDesc("Chhwcm9kdWN0L3YxL3Byb2R1Y3QucHJvdG8SCnByb2R1Y3QudjEidAoNUHJvZHVjdEVudGl0eRIKCgJpZBgBIAEoAxIRCglzZXJpYWxfaWQYAiABKAkSGAoQcHJvZHVjdF9tb2RlbF9pZBgDIAEoAxIUCgxkYXRlX2NyZWF0ZWQYBCABKAMSFAoMZGF0ZV91cGRhdGVkGAUgASgDIlEKEUdldFByb2R1Y3RSZXF1ZXN0Eg8KAmlkGAEgASgDSACIAQESFgoJc2VyaWFsX2lkGAIgASgJSAGIAQFCBQoDX2lkQgwKCl9zZXJpYWxfaWQiQAoSR2V0UHJvZHVjdFJlc3BvbnNlEioKB3Byb2R1Y3QYASABKAsyGS5wcm9kdWN0LnYxLlByb2R1Y3RFbnRpdHki4AEKE0xpc3RQcm9kdWN0c1JlcXVlc3QSLQoKcGFnaW5hdGlvbhgBIAEoCzIZLmNvbW1vbi5QYWdpbmF0aW9uUmVxdWVzdBIdChBwcm9kdWN0X21vZGVsX2lkGAIgASgDSACIAQESHgoRZGF0ZV9jcmVhdGVkX2Zyb20YAyABKANIAYgBARIcCg9kYXRlX2NyZWF0ZWRfdG8YBCABKANIAogBAUITChFfcHJvZHVjdF9tb2RlbF9pZEIUChJfZGF0ZV9jcmVhdGVkX2Zyb21CEgoQX2RhdGVfY3JlYXRlZF90byJzChRMaXN0UHJvZHVjdHNSZXNwb25zZRIuCgpwYWdpbmF0aW9uGAEgASgLMhouY29tbW9uLlBhZ2luYXRpb25SZXNwb25zZRIrCghwcm9kdWN0cxgCIAMoCzIZLnByb2R1Y3QudjEuUHJvZHVjdEVudGl0eSJDChRDcmVhdGVQcm9kdWN0UmVxdWVzdBIRCglzZXJpYWxfaWQYASABKAkSGAoQcHJvZHVjdF9tb2RlbF9pZBgCIAEoAyJDChVDcmVhdGVQcm9kdWN0UmVzcG9uc2USKgoHcHJvZHVjdBgBIAEoCzIZLnByb2R1Y3QudjEuUHJvZHVjdEVudGl0eSJ8ChRVcGRhdGVQcm9kdWN0UmVxdWVzdBIKCgJpZBgBIAEoAxIWCglzZXJpYWxfaWQYAiABKAlIAIgBARIdChBwcm9kdWN0X21vZGVsX2lkGAMgASgDSAGIAQFCDAoKX3NlcmlhbF9pZEITChFfcHJvZHVjdF9tb2RlbF9pZCIXChVVcGRhdGVQcm9kdWN0UmVzcG9uc2UiVAoURGVsZXRlUHJvZHVjdFJlcXVlc3QSDwoCaWQYASABKANIAIgBARIWCglzZXJpYWxfaWQYAiABKAlIAYgBAUIFCgNfaWRCDAoKX3NlcmlhbF9pZCIXChVEZWxldGVQcm9kdWN0UmVzcG9uc2VCrwEKDmNvbS5wcm9kdWN0LnYxQgxQcm9kdWN0UHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9wcm9kdWN0L3YxO3Byb2R1Y3R2MaICA1BYWKoCClByb2R1Y3QuVjHKAgpQcm9kdWN0XFYx4gIWUHJvZHVjdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2R1Y3Q6OlYxYgZwcm90bzM", [file_common_pagination]);

/**
 * Describes the message product.v1.ProductEntity.
 * Use `create(ProductEntitySchema)` to create a new message.
 */
export const ProductEntitySchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 0);

/**
 * Describes the message product.v1.GetProductRequest.
 * Use `create(GetProductRequestSchema)` to create a new message.
 */
export const GetProductRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 1);

/**
 * Describes the message product.v1.GetProductResponse.
 * Use `create(GetProductResponseSchema)` to create a new message.
 */
export const GetProductResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 2);

/**
 * Describes the message product.v1.ListProductsRequest.
 * Use `create(ListProductsRequestSchema)` to create a new message.
 */
export const ListProductsRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 3);

/**
 * Describes the message product.v1.ListProductsResponse.
 * Use `create(ListProductsResponseSchema)` to create a new message.
 */
export const ListProductsResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 4);

/**
 * Describes the message product.v1.CreateProductRequest.
 * Use `create(CreateProductRequestSchema)` to create a new message.
 */
export const CreateProductRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 5);

/**
 * Describes the message product.v1.CreateProductResponse.
 * Use `create(CreateProductResponseSchema)` to create a new message.
 */
export const CreateProductResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 6);

/**
 * Describes the message product.v1.UpdateProductRequest.
 * Use `create(UpdateProductRequestSchema)` to create a new message.
 */
export const UpdateProductRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 7);

/**
 * Describes the message product.v1.UpdateProductResponse.
 * Use `create(UpdateProductResponseSchema)` to create a new message.
 */
export const UpdateProductResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 8);

/**
 * Describes the message product.v1.DeleteProductRequest.
 * Use `create(DeleteProductRequestSchema)` to create a new message.
 */
export const DeleteProductRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 9);

/**
 * Describes the message product.v1.DeleteProductResponse.
 * Use `create(DeleteProductResponseSchema)` to create a new message.
 */
export const DeleteProductResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_product, 10);

