// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/product.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { PaginationRequest, PaginationResponse } from "../../common/pagination_pb";

/**
 * Describes the file product/v1/product.proto.
 */
export declare const file_product_v1_product: GenFile;

/**
 * PRODUCT ENTITY
 *
 * @generated from message product.v1.ProductEntity
 */
export declare type ProductEntity = Message<"product.v1.ProductEntity"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string serial_id = 2;
   */
  serialId: string;

  /**
   * @generated from field: int64 product_model_id = 3;
   */
  productModelId: bigint;

  /**
   * @generated from field: int64 date_created = 4;
   */
  dateCreated: bigint;

  /**
   * @generated from field: int64 date_updated = 5;
   */
  dateUpdated: bigint;
};

/**
 * Describes the message product.v1.ProductEntity.
 * Use `create(ProductEntitySchema)` to create a new message.
 */
export declare const ProductEntitySchema: GenMessage<ProductEntity>;

/**
 * @generated from message product.v1.GetProductRequest
 */
export declare type GetProductRequest = Message<"product.v1.GetProductRequest"> & {
  /**
   * @generated from field: optional int64 id = 1;
   */
  id?: bigint;

  /**
   * @generated from field: optional string serial_id = 2;
   */
  serialId?: string;
};

/**
 * Describes the message product.v1.GetProductRequest.
 * Use `create(GetProductRequestSchema)` to create a new message.
 */
export declare const GetProductRequestSchema: GenMessage<GetProductRequest>;

/**
 * @generated from message product.v1.GetProductResponse
 */
export declare type GetProductResponse = Message<"product.v1.GetProductResponse"> & {
  /**
   * @generated from field: product.v1.ProductEntity data = 1;
   */
  data?: ProductEntity;
};

/**
 * Describes the message product.v1.GetProductResponse.
 * Use `create(GetProductResponseSchema)` to create a new message.
 */
export declare const GetProductResponseSchema: GenMessage<GetProductResponse>;

/**
 * @generated from message product.v1.ListProductsRequest
 */
export declare type ListProductsRequest = Message<"product.v1.ListProductsRequest"> & {
  /**
   * @generated from field: common.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional int64 product_model_id = 2;
   */
  productModelId?: bigint;

  /**
   * @generated from field: optional int64 date_created_from = 3;
   */
  dateCreatedFrom?: bigint;

  /**
   * @generated from field: optional int64 date_created_to = 4;
   */
  dateCreatedTo?: bigint;
};

/**
 * Describes the message product.v1.ListProductsRequest.
 * Use `create(ListProductsRequestSchema)` to create a new message.
 */
export declare const ListProductsRequestSchema: GenMessage<ListProductsRequest>;

/**
 * @generated from message product.v1.ListProductsResponse
 */
export declare type ListProductsResponse = Message<"product.v1.ListProductsResponse"> & {
  /**
   * @generated from field: repeated product.v1.ProductEntity data = 1;
   */
  data: ProductEntity[];

  /**
   * @generated from field: common.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message product.v1.ListProductsResponse.
 * Use `create(ListProductsResponseSchema)` to create a new message.
 */
export declare const ListProductsResponseSchema: GenMessage<ListProductsResponse>;

/**
 * @generated from message product.v1.CreateProductRequest
 */
export declare type CreateProductRequest = Message<"product.v1.CreateProductRequest"> & {
  /**
   * @generated from field: string serial_id = 1;
   */
  serialId: string;

  /**
   * @generated from field: int64 product_model_id = 2;
   */
  productModelId: bigint;
};

/**
 * Describes the message product.v1.CreateProductRequest.
 * Use `create(CreateProductRequestSchema)` to create a new message.
 */
export declare const CreateProductRequestSchema: GenMessage<CreateProductRequest>;

/**
 * @generated from message product.v1.CreateProductResponse
 */
export declare type CreateProductResponse = Message<"product.v1.CreateProductResponse"> & {
  /**
   * @generated from field: product.v1.ProductEntity data = 1;
   */
  data?: ProductEntity;
};

/**
 * Describes the message product.v1.CreateProductResponse.
 * Use `create(CreateProductResponseSchema)` to create a new message.
 */
export declare const CreateProductResponseSchema: GenMessage<CreateProductResponse>;

/**
 * @generated from message product.v1.UpdateProductRequest
 */
export declare type UpdateProductRequest = Message<"product.v1.UpdateProductRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: optional string serial_id = 2;
   */
  serialId?: string;

  /**
   * @generated from field: optional int64 product_model_id = 3;
   */
  productModelId?: bigint;
};

/**
 * Describes the message product.v1.UpdateProductRequest.
 * Use `create(UpdateProductRequestSchema)` to create a new message.
 */
export declare const UpdateProductRequestSchema: GenMessage<UpdateProductRequest>;

/**
 * @generated from message product.v1.UpdateProductResponse
 */
export declare type UpdateProductResponse = Message<"product.v1.UpdateProductResponse"> & {
};

/**
 * Describes the message product.v1.UpdateProductResponse.
 * Use `create(UpdateProductResponseSchema)` to create a new message.
 */
export declare const UpdateProductResponseSchema: GenMessage<UpdateProductResponse>;

/**
 * @generated from message product.v1.DeleteProductRequest
 */
export declare type DeleteProductRequest = Message<"product.v1.DeleteProductRequest"> & {
  /**
   * @generated from field: optional int64 id = 1;
   */
  id?: bigint;

  /**
   * @generated from field: optional string serial_id = 2;
   */
  serialId?: string;
};

/**
 * Describes the message product.v1.DeleteProductRequest.
 * Use `create(DeleteProductRequestSchema)` to create a new message.
 */
export declare const DeleteProductRequestSchema: GenMessage<DeleteProductRequest>;

/**
 * @generated from message product.v1.DeleteProductResponse
 */
export declare type DeleteProductResponse = Message<"product.v1.DeleteProductResponse"> & {
};

/**
 * Describes the message product.v1.DeleteProductResponse.
 * Use `create(DeleteProductResponseSchema)` to create a new message.
 */
export declare const DeleteProductResponseSchema: GenMessage<DeleteProductResponse>;

