// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file product/v1/service.proto (package product.v1, syntax proto3)
/* eslint-disable */

import { ProductService } from "./service_pb";

/**
 * PRODUCT MODEL
 *
 * @generated from rpc product.v1.ProductService.GetProductModel
 */
export const getProductModel = ProductService.method.getProductModel;

/**
 * @generated from rpc product.v1.ProductService.ListProductModels
 */
export const listProductModels = ProductService.method.listProductModels;

/**
 * @generated from rpc product.v1.ProductService.CreateProductModel
 */
export const createProductModel = ProductService.method.createProductModel;

/**
 * @generated from rpc product.v1.ProductService.UpdateProductModel
 */
export const updateProductModel = ProductService.method.updateProductModel;

/**
 * @generated from rpc product.v1.ProductService.DeleteProductModel
 */
export const deleteProductModel = ProductService.method.deleteProductModel;

/**
 * PRODUCT TYPES
 *
 * @generated from rpc product.v1.ProductService.ListProductTypes
 */
export const listProductTypes = ProductService.method.listProductTypes;

/**
 * PRODUCT
 *
 * @generated from rpc product.v1.ProductService.GetProduct
 */
export const getProduct = ProductService.method.getProduct;

/**
 * @generated from rpc product.v1.ProductService.ListProducts
 */
export const listProducts = ProductService.method.listProducts;

/**
 * @generated from rpc product.v1.ProductService.CreateProduct
 */
export const createProduct = ProductService.method.createProduct;

/**
 * @generated from rpc product.v1.ProductService.UpdateProduct
 */
export const updateProduct = ProductService.method.updateProduct;

/**
 * @generated from rpc product.v1.ProductService.DeleteProduct
 */
export const deleteProduct = ProductService.method.deleteProduct;

/**
 * PRODUCT SERIAL
 *
 * @generated from rpc product.v1.ProductService.GetProductSerial
 */
export const getProductSerial = ProductService.method.getProductSerial;

/**
 * @generated from rpc product.v1.ProductService.ListProductSerials
 */
export const listProductSerials = ProductService.method.listProductSerials;

/**
 * @generated from rpc product.v1.ProductService.CreateProductSerial
 */
export const createProductSerial = ProductService.method.createProductSerial;

/**
 * @generated from rpc product.v1.ProductService.UpdateProductSerial
 */
export const updateProductSerial = ProductService.method.updateProductSerial;

/**
 * @generated from rpc product.v1.ProductService.DeleteProductSerial
 */
export const deleteProductSerial = ProductService.method.deleteProductSerial;

/**
 * BRAND
 *
 * @generated from rpc product.v1.ProductService.GetBrand
 */
export const getBrand = ProductService.method.getBrand;

/**
 * @generated from rpc product.v1.ProductService.ListBrands
 */
export const listBrands = ProductService.method.listBrands;

/**
 * @generated from rpc product.v1.ProductService.CreateBrand
 */
export const createBrand = ProductService.method.createBrand;

/**
 * @generated from rpc product.v1.ProductService.UpdateBrand
 */
export const updateBrand = ProductService.method.updateBrand;

/**
 * @generated from rpc product.v1.ProductService.DeleteBrand
 */
export const deleteBrand = ProductService.method.deleteBrand;

/**
 * SALE
 *
 * @generated from rpc product.v1.ProductService.GetSale
 */
export const getSale = ProductService.method.getSale;

/**
 * @generated from rpc product.v1.ProductService.ListSales
 */
export const listSales = ProductService.method.listSales;

/**
 * @generated from rpc product.v1.ProductService.CreateSale
 */
export const createSale = ProductService.method.createSale;

/**
 * @generated from rpc product.v1.ProductService.UpdateSale
 */
export const updateSale = ProductService.method.updateSale;

/**
 * @generated from rpc product.v1.ProductService.DeleteSale
 */
export const deleteSale = ProductService.method.deleteSale;

/**
 * TAG
 *
 * @generated from rpc product.v1.ProductService.GetTag
 */
export const getTag = ProductService.method.getTag;

/**
 * @generated from rpc product.v1.ProductService.ListTags
 */
export const listTags = ProductService.method.listTags;

/**
 * @generated from rpc product.v1.ProductService.CreateTag
 */
export const createTag = ProductService.method.createTag;

/**
 * @generated from rpc product.v1.ProductService.UpdateTag
 */
export const updateTag = ProductService.method.updateTag;

/**
 * @generated from rpc product.v1.ProductService.DeleteTag
 */
export const deleteTag = ProductService.method.deleteTag;

/**
 * COMMENT
 *
 * @generated from rpc product.v1.ProductService.GetComment
 */
export const getComment = ProductService.method.getComment;

/**
 * @generated from rpc product.v1.ProductService.ListComments
 */
export const listComments = ProductService.method.listComments;

/**
 * @generated from rpc product.v1.ProductService.CreateComment
 */
export const createComment = ProductService.method.createComment;

/**
 * @generated from rpc product.v1.ProductService.UpdateComment
 */
export const updateComment = ProductService.method.updateComment;

/**
 * @generated from rpc product.v1.ProductService.DeleteComment
 */
export const deleteComment = ProductService.method.deleteComment;
