// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/service.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { CreateProductModelRequestSchema, CreateProductModelResponseSchema, DeleteProductModelRequestSchema, DeleteProductModelResponseSchema, GetProductModelRequestSchema, GetProductModelResponseSchema, ListProductModelsRequestSchema, ListProductModelsResponseSchema, UpdateProductModelRequestSchema, UpdateProductModelResponseSchema } from "./product-model_pb";
import type { CreateProductRequestSchema, CreateProductResponseSchema, DeleteProductRequestSchema, DeleteProductResponseSchema, GetProductRequestSchema, GetProductResponseSchema, ListProductsRequestSchema, ListProductsResponseSchema, UpdateProductRequestSchema, UpdateProductResponseSchema } from "./product_pb";

/**
 * Describes the file product/v1/service.proto.
 */
export declare const file_product_v1_service: GenFile;

/**
 * @generated from service product.v1.ProductService
 */
export declare const ProductService: GenService<{
  /**
   * @generated from rpc product.v1.ProductService.GetProductModel
   */
  getProductModel: {
    methodKind: "unary";
    input: typeof GetProductModelRequestSchema;
    output: typeof GetProductModelResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.ListProductModels
   */
  listProductModels: {
    methodKind: "unary";
    input: typeof ListProductModelsRequestSchema;
    output: typeof ListProductModelsResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.CreateProductModel
   */
  createProductModel: {
    methodKind: "unary";
    input: typeof CreateProductModelRequestSchema;
    output: typeof CreateProductModelResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.UpdateProductModel
   */
  updateProductModel: {
    methodKind: "unary";
    input: typeof UpdateProductModelRequestSchema;
    output: typeof UpdateProductModelResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.DeleteProductModel
   */
  deleteProductModel: {
    methodKind: "unary";
    input: typeof DeleteProductModelRequestSchema;
    output: typeof DeleteProductModelResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.GetProduct
   */
  getProduct: {
    methodKind: "unary";
    input: typeof GetProductRequestSchema;
    output: typeof GetProductResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.ListProducts
   */
  listProducts: {
    methodKind: "unary";
    input: typeof ListProductsRequestSchema;
    output: typeof ListProductsResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.CreateProduct
   */
  createProduct: {
    methodKind: "unary";
    input: typeof CreateProductRequestSchema;
    output: typeof CreateProductResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.UpdateProduct
   */
  updateProduct: {
    methodKind: "unary";
    input: typeof UpdateProductRequestSchema;
    output: typeof UpdateProductResponseSchema;
  },
  /**
   * @generated from rpc product.v1.ProductService.DeleteProduct
   */
  deleteProduct: {
    methodKind: "unary";
    input: typeof DeleteProductRequestSchema;
    output: typeof DeleteProductResponseSchema;
  },
}>;

