// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/tag.proto (package product.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_common_pagination } from "../../common/pagination_pb";

/**
 * Describes the file product/v1/tag.proto.
 */
export const file_product_v1_tag = /*@__PURE__*/
  fileDesc("ChRwcm9kdWN0L3YxL3RhZy5wcm90bxIKcHJvZHVjdC52MSItCglUYWdFbnRpdHkSCwoDdGFnGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJIhwKDUdldFRhZ1JlcXVlc3QSCwoDdGFnGAEgASgJIjUKDkdldFRhZ1Jlc3BvbnNlEiMKBGRhdGEYASABKAsyFS5wcm9kdWN0LnYxLlRhZ0VudGl0eSKEAQoPTGlzdFRhZ3NSZXF1ZXN0Ei0KCnBhZ2luYXRpb24YASABKAsyGS5jb21tb24uUGFnaW5hdGlvblJlcXVlc3QSEAoDdGFnGAIgASgJSACIAQESGAoLZGVzY3JpcHRpb24YAyABKAlIAYgBAUIGCgRfdGFnQg4KDF9kZXNjcmlwdGlvbiJnChBMaXN0VGFnc1Jlc3BvbnNlEiMKBGRhdGEYASADKAsyFS5wcm9kdWN0LnYxLlRhZ0VudGl0eRIuCgpwYWdpbmF0aW9uGAIgASgLMhouY29tbW9uLlBhZ2luYXRpb25SZXNwb25zZSI0ChBDcmVhdGVUYWdSZXF1ZXN0EgsKA3RhZxgBIAEoCRITCgtkZXNjcmlwdGlvbhgCIAEoCSI4ChFDcmVhdGVUYWdSZXNwb25zZRIjCgRkYXRhGAEgASgLMhUucHJvZHVjdC52MS5UYWdFbnRpdHkiawoQVXBkYXRlVGFnUmVxdWVzdBILCgN0YWcYASABKAkSFAoHbmV3X3RhZxgCIAEoCUgAiAEBEhgKC2Rlc2NyaXB0aW9uGAMgASgJSAGIAQFCCgoIX25ld190YWdCDgoMX2Rlc2NyaXB0aW9uIhMKEVVwZGF0ZVRhZ1Jlc3BvbnNlIh8KEERlbGV0ZVRhZ1JlcXVlc3QSCwoDdGFnGAEgASgJIhMKEURlbGV0ZVRhZ1Jlc3BvbnNlQqsBCg5jb20ucHJvZHVjdC52MUIIVGFnUHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9wcm9kdWN0L3YxO3Byb2R1Y3R2MaICA1BYWKoCClByb2R1Y3QuVjHKAgpQcm9kdWN0XFYx4gIWUHJvZHVjdFxWMVxHUEJNZXRhZGF0YeoCC1Byb2R1Y3Q6OlYxYgZwcm90bzM", [file_common_pagination]);

/**
 * Describes the message product.v1.TagEntity.
 * Use `create(TagEntitySchema)` to create a new message.
 */
export const TagEntitySchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 0);

/**
 * Describes the message product.v1.GetTagRequest.
 * Use `create(GetTagRequestSchema)` to create a new message.
 */
export const GetTagRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 1);

/**
 * Describes the message product.v1.GetTagResponse.
 * Use `create(GetTagResponseSchema)` to create a new message.
 */
export const GetTagResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 2);

/**
 * Describes the message product.v1.ListTagsRequest.
 * Use `create(ListTagsRequestSchema)` to create a new message.
 */
export const ListTagsRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 3);

/**
 * Describes the message product.v1.ListTagsResponse.
 * Use `create(ListTagsResponseSchema)` to create a new message.
 */
export const ListTagsResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 4);

/**
 * Describes the message product.v1.CreateTagRequest.
 * Use `create(CreateTagRequestSchema)` to create a new message.
 */
export const CreateTagRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 5);

/**
 * Describes the message product.v1.CreateTagResponse.
 * Use `create(CreateTagResponseSchema)` to create a new message.
 */
export const CreateTagResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 6);

/**
 * Describes the message product.v1.UpdateTagRequest.
 * Use `create(UpdateTagRequestSchema)` to create a new message.
 */
export const UpdateTagRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 7);

/**
 * Describes the message product.v1.UpdateTagResponse.
 * Use `create(UpdateTagResponseSchema)` to create a new message.
 */
export const UpdateTagResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 8);

/**
 * Describes the message product.v1.DeleteTagRequest.
 * Use `create(DeleteTagRequestSchema)` to create a new message.
 */
export const DeleteTagRequestSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 9);

/**
 * Describes the message product.v1.DeleteTagResponse.
 * Use `create(DeleteTagResponseSchema)` to create a new message.
 */
export const DeleteTagResponseSchema = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 10);

