// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file product/v1/tag.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { PaginationRequest, PaginationResponse } from "../../common/pagination_pb";
import { file_common_pagination } from "../../common/pagination_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file product/v1/tag.proto.
 */
export const file_product_v1_tag: GenFile = /*@__PURE__*/
  fileDesc("ChRwcm9kdWN0L3YxL3RhZy5wcm90bxIKcHJvZHVjdC52MSJECglUYWdFbnRpdHkSCwoDdGFnGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJEhUKDXByb2R1Y3RfY291bnQYAyABKAUiHAoNR2V0VGFnUmVxdWVzdBILCgN0YWcYASABKAkiNQoOR2V0VGFnUmVzcG9uc2USIwoEZGF0YRgBIAEoCzIVLnByb2R1Y3QudjEuVGFnRW50aXR5IoQBCg9MaXN0VGFnc1JlcXVlc3QSLQoKcGFnaW5hdGlvbhgBIAEoCzIZLmNvbW1vbi5QYWdpbmF0aW9uUmVxdWVzdBIQCgN0YWcYAiABKAlIAIgBARIYCgtkZXNjcmlwdGlvbhgDIAEoCUgBiAEBQgYKBF90YWdCDgoMX2Rlc2NyaXB0aW9uImcKEExpc3RUYWdzUmVzcG9uc2USIwoEZGF0YRgBIAMoCzIVLnByb2R1Y3QudjEuVGFnRW50aXR5Ei4KCnBhZ2luYXRpb24YAiABKAsyGi5jb21tb24uUGFnaW5hdGlvblJlc3BvbnNlIjQKEENyZWF0ZVRhZ1JlcXVlc3QSCwoDdGFnGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJIjgKEUNyZWF0ZVRhZ1Jlc3BvbnNlEiMKBGRhdGEYASABKAsyFS5wcm9kdWN0LnYxLlRhZ0VudGl0eSJrChBVcGRhdGVUYWdSZXF1ZXN0EgsKA3RhZxgBIAEoCRIUCgduZXdfdGFnGAIgASgJSACIAQESGAoLZGVzY3JpcHRpb24YAyABKAlIAYgBAUIKCghfbmV3X3RhZ0IOCgxfZGVzY3JpcHRpb24iEwoRVXBkYXRlVGFnUmVzcG9uc2UiHwoQRGVsZXRlVGFnUmVxdWVzdBILCgN0YWcYASABKAkiEwoRRGVsZXRlVGFnUmVzcG9uc2VCqwEKDmNvbS5wcm9kdWN0LnYxQghUYWdQcm90b1ABWkZnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL3Byb2R1Y3QvdjE7cHJvZHVjdHYxogIDUFhYqgIKUHJvZHVjdC5WMcoCClByb2R1Y3RcVjHiAhZQcm9kdWN0XFYxXEdQQk1ldGFkYXRh6gILUHJvZHVjdDo6VjFiBnByb3RvMw", [file_common_pagination]);

/**
 * TAG ENTITY
 *
 * @generated from message product.v1.TagEntity
 */
export type TagEntity = Message<"product.v1.TagEntity"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;

  /**
   * @generated from field: int32 product_count = 3;
   */
  productCount: number;
};

/**
 * Describes the message product.v1.TagEntity.
 * Use `create(TagEntitySchema)` to create a new message.
 */
export const TagEntitySchema: GenMessage<TagEntity> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 0);

/**
 * @generated from message product.v1.GetTagRequest
 */
export type GetTagRequest = Message<"product.v1.GetTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;
};

/**
 * Describes the message product.v1.GetTagRequest.
 * Use `create(GetTagRequestSchema)` to create a new message.
 */
export const GetTagRequestSchema: GenMessage<GetTagRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 1);

/**
 * @generated from message product.v1.GetTagResponse
 */
export type GetTagResponse = Message<"product.v1.GetTagResponse"> & {
  /**
   * @generated from field: product.v1.TagEntity data = 1;
   */
  data?: TagEntity;
};

/**
 * Describes the message product.v1.GetTagResponse.
 * Use `create(GetTagResponseSchema)` to create a new message.
 */
export const GetTagResponseSchema: GenMessage<GetTagResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 2);

/**
 * @generated from message product.v1.ListTagsRequest
 */
export type ListTagsRequest = Message<"product.v1.ListTagsRequest"> & {
  /**
   * @generated from field: common.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional string tag = 2;
   */
  tag?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message product.v1.ListTagsRequest.
 * Use `create(ListTagsRequestSchema)` to create a new message.
 */
export const ListTagsRequestSchema: GenMessage<ListTagsRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 3);

/**
 * @generated from message product.v1.ListTagsResponse
 */
export type ListTagsResponse = Message<"product.v1.ListTagsResponse"> & {
  /**
   * @generated from field: repeated product.v1.TagEntity data = 1;
   */
  data: TagEntity[];

  /**
   * @generated from field: common.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message product.v1.ListTagsResponse.
 * Use `create(ListTagsResponseSchema)` to create a new message.
 */
export const ListTagsResponseSchema: GenMessage<ListTagsResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 4);

/**
 * @generated from message product.v1.CreateTagRequest
 */
export type CreateTagRequest = Message<"product.v1.CreateTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message product.v1.CreateTagRequest.
 * Use `create(CreateTagRequestSchema)` to create a new message.
 */
export const CreateTagRequestSchema: GenMessage<CreateTagRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 5);

/**
 * @generated from message product.v1.CreateTagResponse
 */
export type CreateTagResponse = Message<"product.v1.CreateTagResponse"> & {
  /**
   * @generated from field: product.v1.TagEntity data = 1;
   */
  data?: TagEntity;
};

/**
 * Describes the message product.v1.CreateTagResponse.
 * Use `create(CreateTagResponseSchema)` to create a new message.
 */
export const CreateTagResponseSchema: GenMessage<CreateTagResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 6);

/**
 * @generated from message product.v1.UpdateTagRequest
 */
export type UpdateTagRequest = Message<"product.v1.UpdateTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: optional string new_tag = 2;
   */
  newTag?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message product.v1.UpdateTagRequest.
 * Use `create(UpdateTagRequestSchema)` to create a new message.
 */
export const UpdateTagRequestSchema: GenMessage<UpdateTagRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 7);

/**
 * @generated from message product.v1.UpdateTagResponse
 */
export type UpdateTagResponse = Message<"product.v1.UpdateTagResponse"> & {
};

/**
 * Describes the message product.v1.UpdateTagResponse.
 * Use `create(UpdateTagResponseSchema)` to create a new message.
 */
export const UpdateTagResponseSchema: GenMessage<UpdateTagResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 8);

/**
 * @generated from message product.v1.DeleteTagRequest
 */
export type DeleteTagRequest = Message<"product.v1.DeleteTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;
};

/**
 * Describes the message product.v1.DeleteTagRequest.
 * Use `create(DeleteTagRequestSchema)` to create a new message.
 */
export const DeleteTagRequestSchema: GenMessage<DeleteTagRequest> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 9);

/**
 * @generated from message product.v1.DeleteTagResponse
 */
export type DeleteTagResponse = Message<"product.v1.DeleteTagResponse"> & {
};

/**
 * Describes the message product.v1.DeleteTagResponse.
 * Use `create(DeleteTagResponseSchema)` to create a new message.
 */
export const DeleteTagResponseSchema: GenMessage<DeleteTagResponse> = /*@__PURE__*/
  messageDesc(file_product_v1_tag, 10);

