// @generated by protoc-gen-es v2.2.3
// @generated from file product/v1/tag.proto (package product.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { PaginationRequest, PaginationResponse } from "../../common/pagination_pb";

/**
 * Describes the file product/v1/tag.proto.
 */
export declare const file_product_v1_tag: GenFile;

/**
 * TAG ENTITY
 *
 * @generated from message product.v1.TagEntity
 */
export declare type TagEntity = Message<"product.v1.TagEntity"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message product.v1.TagEntity.
 * Use `create(TagEntitySchema)` to create a new message.
 */
export declare const TagEntitySchema: GenMessage<TagEntity>;

/**
 * @generated from message product.v1.GetTagRequest
 */
export declare type GetTagRequest = Message<"product.v1.GetTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;
};

/**
 * Describes the message product.v1.GetTagRequest.
 * Use `create(GetTagRequestSchema)` to create a new message.
 */
export declare const GetTagRequestSchema: GenMessage<GetTagRequest>;

/**
 * @generated from message product.v1.GetTagResponse
 */
export declare type GetTagResponse = Message<"product.v1.GetTagResponse"> & {
  /**
   * @generated from field: product.v1.TagEntity data = 1;
   */
  data?: TagEntity;
};

/**
 * Describes the message product.v1.GetTagResponse.
 * Use `create(GetTagResponseSchema)` to create a new message.
 */
export declare const GetTagResponseSchema: GenMessage<GetTagResponse>;

/**
 * @generated from message product.v1.ListTagsRequest
 */
export declare type ListTagsRequest = Message<"product.v1.ListTagsRequest"> & {
  /**
   * @generated from field: common.PaginationRequest pagination = 1;
   */
  pagination?: PaginationRequest;

  /**
   * @generated from field: optional string tag = 2;
   */
  tag?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message product.v1.ListTagsRequest.
 * Use `create(ListTagsRequestSchema)` to create a new message.
 */
export declare const ListTagsRequestSchema: GenMessage<ListTagsRequest>;

/**
 * @generated from message product.v1.ListTagsResponse
 */
export declare type ListTagsResponse = Message<"product.v1.ListTagsResponse"> & {
  /**
   * @generated from field: repeated product.v1.TagEntity data = 1;
   */
  data: TagEntity[];

  /**
   * @generated from field: common.PaginationResponse pagination = 2;
   */
  pagination?: PaginationResponse;
};

/**
 * Describes the message product.v1.ListTagsResponse.
 * Use `create(ListTagsResponseSchema)` to create a new message.
 */
export declare const ListTagsResponseSchema: GenMessage<ListTagsResponse>;

/**
 * @generated from message product.v1.CreateTagRequest
 */
export declare type CreateTagRequest = Message<"product.v1.CreateTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message product.v1.CreateTagRequest.
 * Use `create(CreateTagRequestSchema)` to create a new message.
 */
export declare const CreateTagRequestSchema: GenMessage<CreateTagRequest>;

/**
 * @generated from message product.v1.CreateTagResponse
 */
export declare type CreateTagResponse = Message<"product.v1.CreateTagResponse"> & {
  /**
   * @generated from field: product.v1.TagEntity data = 1;
   */
  data?: TagEntity;
};

/**
 * Describes the message product.v1.CreateTagResponse.
 * Use `create(CreateTagResponseSchema)` to create a new message.
 */
export declare const CreateTagResponseSchema: GenMessage<CreateTagResponse>;

/**
 * @generated from message product.v1.UpdateTagRequest
 */
export declare type UpdateTagRequest = Message<"product.v1.UpdateTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;

  /**
   * @generated from field: optional string new_tag = 2;
   */
  newTag?: string;

  /**
   * @generated from field: optional string description = 3;
   */
  description?: string;
};

/**
 * Describes the message product.v1.UpdateTagRequest.
 * Use `create(UpdateTagRequestSchema)` to create a new message.
 */
export declare const UpdateTagRequestSchema: GenMessage<UpdateTagRequest>;

/**
 * @generated from message product.v1.UpdateTagResponse
 */
export declare type UpdateTagResponse = Message<"product.v1.UpdateTagResponse"> & {
};

/**
 * Describes the message product.v1.UpdateTagResponse.
 * Use `create(UpdateTagResponseSchema)` to create a new message.
 */
export declare const UpdateTagResponseSchema: GenMessage<UpdateTagResponse>;

/**
 * @generated from message product.v1.DeleteTagRequest
 */
export declare type DeleteTagRequest = Message<"product.v1.DeleteTagRequest"> & {
  /**
   * @generated from field: string tag = 1;
   */
  tag: string;
};

/**
 * Describes the message product.v1.DeleteTagRequest.
 * Use `create(DeleteTagRequestSchema)` to create a new message.
 */
export declare const DeleteTagRequestSchema: GenMessage<DeleteTagRequest>;

/**
 * @generated from message product.v1.DeleteTagResponse
 */
export declare type DeleteTagResponse = Message<"product.v1.DeleteTagResponse"> & {
};

/**
 * Describes the message product.v1.DeleteTagResponse.
 * Use `create(DeleteTagResponseSchema)` to create a new message.
 */
export declare const DeleteTagResponseSchema: GenMessage<DeleteTagResponse>;

