// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file file/v1/service.proto (package file.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file file/v1/service.proto.
 */
export const file_file_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChVmaWxlL3YxL3NlcnZpY2UucHJvdG8SB2ZpbGUudjEiLgoNVXBsb2FkUmVxdWVzdBIMCgRuYW1lGAEgASgJEg8KB2NvbnRlbnQYAiABKAwiHQoOVXBsb2FkUmVzcG9uc2USCwoDdXJsGAEgASgJMkoKC0ZpbGVTZXJ2aWNlEjsKBlVwbG9hZBIWLmZpbGUudjEuVXBsb2FkUmVxdWVzdBoXLmZpbGUudjEuVXBsb2FkUmVzcG9uc2UiAEKaAQoLY29tLmZpbGUudjFCDFNlcnZpY2VQcm90b1ABWkBnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL2ZpbGUvdjE7ZmlsZXYxogIDRlhYqgIHRmlsZS5WMcoCB0ZpbGVcVjHiAhNGaWxlXFYxXEdQQk1ldGFkYXRh6gIIRmlsZTo6VjFiBnByb3RvMw");

/**
 * @generated from message file.v1.UploadRequest
 */
export type UploadRequest = Message<"file.v1.UploadRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: bytes content = 2;
   */
  content: Uint8Array;
};

/**
 * Describes the message file.v1.UploadRequest.
 * Use `create(UploadRequestSchema)` to create a new message.
 */
export const UploadRequestSchema: GenMessage<UploadRequest> = /*@__PURE__*/
  messageDesc(file_file_v1_service, 0);

/**
 * @generated from message file.v1.UploadResponse
 */
export type UploadResponse = Message<"file.v1.UploadResponse"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;
};

/**
 * Describes the message file.v1.UploadResponse.
 * Use `create(UploadResponseSchema)` to create a new message.
 */
export const UploadResponseSchema: GenMessage<UploadResponse> = /*@__PURE__*/
  messageDesc(file_file_v1_service, 1);

/**
 * @generated from service file.v1.FileService
 */
export const FileService: GenService<{
  /**
   * @generated from rpc file.v1.FileService.Upload
   */
  upload: {
    methodKind: "unary";
    input: typeof UploadRequestSchema;
    output: typeof UploadResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_file_v1_service, 0);

