// @generated by protoc-gen-es v2.2.3
// @generated from file payment/v1/payment.proto (package payment.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_common_pagination } from "../../common/pagination_pb";
import { file_common_status } from "../../common/status_pb";

/**
 * Describes the file payment/v1/payment.proto.
 */
export const file_payment_v1_payment = /*@__PURE__*/
  fileDesc("ChhwYXltZW50L3YxL3BheW1lbnQucHJvdG8SCnBheW1lbnQudjEipwEKB1BheW1lbnQSCgoCaWQYASABKAMSDwoHdXNlcl9pZBgCIAEoAxIpCgZtZXRob2QYAyABKA4yGS5wYXltZW50LnYxLlBheW1lbnRNZXRob2QSHgoGc3RhdHVzGAQgASgOMg4uY29tbW9uLlN0YXR1cxIPCgdhZGRyZXNzGAUgASgJEg0KBXRvdGFsGAYgASgDEhQKDGRhdGVfY3JlYXRlZBgHIAEoAyInChFHZXRQYXltZW50UmVxdWVzdBISCgpwYXltZW50X2lkGAEgASgJIjoKEkdldFBheW1lbnRSZXNwb25zZRIkCgdwYXltZW50GAEgASgLMhMucGF5bWVudC52MS5QYXltZW50IrkCChNMaXN0UGF5bWVudHNSZXF1ZXN0Ei0KCnBhZ2luYXRpb24YASABKAsyGS5jb21tb24uUGFnaW5hdGlvblJlcXVlc3QSFAoHdXNlcl9pZBgCIAEoA0gAiAEBEi4KBm1ldGhvZBgDIAEoDjIZLnBheW1lbnQudjEuUGF5bWVudE1ldGhvZEgBiAEBEiMKBnN0YXR1cxgEIAEoDjIOLmNvbW1vbi5TdGF0dXNIAogBARIeChFkYXRlX2NyZWF0ZWRfZnJvbRgFIAEoA0gDiAEBEhwKD2RhdGVfY3JlYXRlZF90bxgGIAEoA0gEiAEBQgoKCF91c2VyX2lkQgkKB19tZXRob2RCCQoHX3N0YXR1c0IUChJfZGF0ZV9jcmVhdGVkX2Zyb21CEgoQX2RhdGVfY3JlYXRlZF90byJtChRMaXN0UGF5bWVudHNSZXNwb25zZRIuCgpwYWdpbmF0aW9uGAEgASgLMhouY29tbW9uLlBhZ2luYXRpb25SZXNwb25zZRIlCghwYXltZW50cxgCIAMoCzITLnBheW1lbnQudjEuUGF5bWVudCJuChRDcmVhdGVQYXltZW50UmVxdWVzdBISCgpyZXF1ZXN0X2lkGAEgASgDEjEKDnBheW1lbnRfbWV0aG9kGAIgASgOMhkucGF5bWVudC52MS5QYXltZW50TWV0aG9kEg8KB2FkZHJlc3MYAyABKAkiXgoVQ3JlYXRlUGF5bWVudFJlc3BvbnNlEhIKCnJlcXVlc3RfaWQYASABKAMSCwoDdXJsGAIgASgJEiQKB3BheW1lbnQYAyABKAsyEy5wYXltZW50LnYxLlBheW1lbnQiWgoUVXBkYXRlUGF5bWVudFJlcXVlc3QSEgoKcGF5bWVudF9pZBgBIAEoCRIjCgZzdGF0dXMYAiABKA4yDi5jb21tb24uU3RhdHVzSACIAQFCCQoHX3N0YXR1cyIXChVVcGRhdGVQYXltZW50UmVzcG9uc2UiKgoUQ2FuY2VsUGF5bWVudFJlcXVlc3QSEgoKcGF5bWVudF9pZBgBIAEoCSIXChVDYW5jZWxQYXltZW50UmVzcG9uc2UqewoNUGF5bWVudE1ldGhvZBIeChpQQVlNRU5UX01FVEhPRF9VTlNQRUNJRklFRBAAEhcKE1BBWU1FTlRfTUVUSE9EX0NBU0gQARIXChNQQVlNRU5UX01FVEhPRF9NT01PEAISGAoUUEFZTUVOVF9NRVRIT0RfVk5QQVkQA0KvAQoOY29tLnBheW1lbnQudjFCDFBheW1lbnRQcm90b1ABWkZnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL3BheW1lbnQvdjE7cGF5bWVudHYxogIDUFhYqgIKUGF5bWVudC5WMcoCClBheW1lbnRcVjHiAhZQYXltZW50XFYxXEdQQk1ldGFkYXRh6gILUGF5bWVudDo6VjFiBnByb3RvMw", [file_common_pagination, file_common_status]);

/**
 * Describes the message payment.v1.Payment.
 * Use `create(PaymentSchema)` to create a new message.
 */
export const PaymentSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 0);

/**
 * Describes the message payment.v1.GetPaymentRequest.
 * Use `create(GetPaymentRequestSchema)` to create a new message.
 */
export const GetPaymentRequestSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 1);

/**
 * Describes the message payment.v1.GetPaymentResponse.
 * Use `create(GetPaymentResponseSchema)` to create a new message.
 */
export const GetPaymentResponseSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 2);

/**
 * Describes the message payment.v1.ListPaymentsRequest.
 * Use `create(ListPaymentsRequestSchema)` to create a new message.
 */
export const ListPaymentsRequestSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 3);

/**
 * Describes the message payment.v1.ListPaymentsResponse.
 * Use `create(ListPaymentsResponseSchema)` to create a new message.
 */
export const ListPaymentsResponseSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 4);

/**
 * Describes the message payment.v1.CreatePaymentRequest.
 * Use `create(CreatePaymentRequestSchema)` to create a new message.
 */
export const CreatePaymentRequestSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 5);

/**
 * Describes the message payment.v1.CreatePaymentResponse.
 * Use `create(CreatePaymentResponseSchema)` to create a new message.
 */
export const CreatePaymentResponseSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 6);

/**
 * Describes the message payment.v1.UpdatePaymentRequest.
 * Use `create(UpdatePaymentRequestSchema)` to create a new message.
 */
export const UpdatePaymentRequestSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 7);

/**
 * Describes the message payment.v1.UpdatePaymentResponse.
 * Use `create(UpdatePaymentResponseSchema)` to create a new message.
 */
export const UpdatePaymentResponseSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 8);

/**
 * Describes the message payment.v1.CancelPaymentRequest.
 * Use `create(CancelPaymentRequestSchema)` to create a new message.
 */
export const CancelPaymentRequestSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 9);

/**
 * Describes the message payment.v1.CancelPaymentResponse.
 * Use `create(CancelPaymentResponseSchema)` to create a new message.
 */
export const CancelPaymentResponseSchema = /*@__PURE__*/
  messageDesc(file_payment_v1_payment, 10);

/**
 * Describes the enum payment.v1.PaymentMethod.
 */
export const PaymentMethodSchema = /*@__PURE__*/
  enumDesc(file_payment_v1_payment, 0);

/**
 * @generated from enum payment.v1.PaymentMethod
 */
export const PaymentMethod = /*@__PURE__*/
  tsEnum(PaymentMethodSchema);

