// @generated by protoc-gen-es v2.2.3
// @generated from file payment/v1/service.proto (package payment.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { CancelPaymentRequestSchema, CancelPaymentResponseSchema, CreatePaymentRequestSchema, CreatePaymentResponseSchema, GetPaymentRequestSchema, GetPaymentResponseSchema, ListPaymentsRequestSchema, ListPaymentsResponseSchema, UpdatePaymentRequestSchema, UpdatePaymentResponseSchema } from "./payment_pb";
import type { CancelRefundRequestSchema, CancelRefundResponseSchema, CreateRefundRequestSchema, CreateRefundResponseSchema, GetRefundRequestSchema, GetRefundResponseSchema, ListRefundsRequestSchema, ListRefundsResponseSchema, UpdateRefundRequestSchema, UpdateRefundResponseSchema } from "./refund_pb";

/**
 * Describes the file payment/v1/service.proto.
 */
export declare const file_payment_v1_service: GenFile;

/**
 * @generated from service payment.v1.PaymentService
 */
export declare const PaymentService: GenService<{
  /**
   * @generated from rpc payment.v1.PaymentService.GetPayment
   */
  getPayment: {
    methodKind: "unary";
    input: typeof GetPaymentRequestSchema;
    output: typeof GetPaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.ListPayments
   */
  listPayments: {
    methodKind: "unary";
    input: typeof ListPaymentsRequestSchema;
    output: typeof ListPaymentsResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CreatePayment
   */
  createPayment: {
    methodKind: "unary";
    input: typeof CreatePaymentRequestSchema;
    output: typeof CreatePaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.UpdatePayment
   */
  updatePayment: {
    methodKind: "unary";
    input: typeof UpdatePaymentRequestSchema;
    output: typeof UpdatePaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CancelPayment
   */
  cancelPayment: {
    methodKind: "unary";
    input: typeof CancelPaymentRequestSchema;
    output: typeof CancelPaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.GetRefund
   */
  getRefund: {
    methodKind: "unary";
    input: typeof GetRefundRequestSchema;
    output: typeof GetRefundResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.ListRefunds
   */
  listRefunds: {
    methodKind: "unary";
    input: typeof ListRefundsRequestSchema;
    output: typeof ListRefundsResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CreateRefund
   */
  createRefund: {
    methodKind: "unary";
    input: typeof CreateRefundRequestSchema;
    output: typeof CreateRefundResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.UpdateRefund
   */
  updateRefund: {
    methodKind: "unary";
    input: typeof UpdateRefundRequestSchema;
    output: typeof UpdateRefundResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CancelRefund
   */
  cancelRefund: {
    methodKind: "unary";
    input: typeof CancelRefundRequestSchema;
    output: typeof CancelRefundResponseSchema;
  },
}>;

