// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file payment/v1/service.proto (package payment.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { CancelPaymentRequestSchema, CancelPaymentResponseSchema, CreatePaymentRequestSchema, CreatePaymentResponseSchema, GetPaymentRequestSchema, GetPaymentResponseSchema, ListPaymentsRequestSchema, ListPaymentsResponseSchema, UpdatePaymentRequestSchema, UpdatePaymentResponseSchema } from "./payment_pb";
import { file_payment_v1_payment } from "./payment_pb";
import type { CancelRefundRequestSchema, CancelRefundResponseSchema, CreateRefundRequestSchema, CreateRefundResponseSchema, GetRefundRequestSchema, GetRefundResponseSchema, ListRefundsRequestSchema, ListRefundsResponseSchema, UpdateRefundRequestSchema, UpdateRefundResponseSchema } from "./refund_pb";
import { file_payment_v1_refund } from "./refund_pb";

/**
 * Describes the file payment/v1/service.proto.
 */
export const file_payment_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChhwYXltZW50L3YxL3NlcnZpY2UucHJvdG8SCnBheW1lbnQudjEy5QYKDlBheW1lbnRTZXJ2aWNlElAKCkdldFBheW1lbnQSHS5wYXltZW50LnYxLkdldFBheW1lbnRSZXF1ZXN0Gh4ucGF5bWVudC52MS5HZXRQYXltZW50UmVzcG9uc2UiA5ACARJWCgxMaXN0UGF5bWVudHMSHy5wYXltZW50LnYxLkxpc3RQYXltZW50c1JlcXVlc3QaIC5wYXltZW50LnYxLkxpc3RQYXltZW50c1Jlc3BvbnNlIgOQAgESVgoNQ3JlYXRlUGF5bWVudBIgLnBheW1lbnQudjEuQ3JlYXRlUGF5bWVudFJlcXVlc3QaIS5wYXltZW50LnYxLkNyZWF0ZVBheW1lbnRSZXNwb25zZSIAElYKDVVwZGF0ZVBheW1lbnQSIC5wYXltZW50LnYxLlVwZGF0ZVBheW1lbnRSZXF1ZXN0GiEucGF5bWVudC52MS5VcGRhdGVQYXltZW50UmVzcG9uc2UiABJWCg1DYW5jZWxQYXltZW50EiAucGF5bWVudC52MS5DYW5jZWxQYXltZW50UmVxdWVzdBohLnBheW1lbnQudjEuQ2FuY2VsUGF5bWVudFJlc3BvbnNlIgASTQoJR2V0UmVmdW5kEhwucGF5bWVudC52MS5HZXRSZWZ1bmRSZXF1ZXN0Gh0ucGF5bWVudC52MS5HZXRSZWZ1bmRSZXNwb25zZSIDkAIBElMKC0xpc3RSZWZ1bmRzEh4ucGF5bWVudC52MS5MaXN0UmVmdW5kc1JlcXVlc3QaHy5wYXltZW50LnYxLkxpc3RSZWZ1bmRzUmVzcG9uc2UiA5ACARJTCgxDcmVhdGVSZWZ1bmQSHy5wYXltZW50LnYxLkNyZWF0ZVJlZnVuZFJlcXVlc3QaIC5wYXltZW50LnYxLkNyZWF0ZVJlZnVuZFJlc3BvbnNlIgASUwoMVXBkYXRlUmVmdW5kEh8ucGF5bWVudC52MS5VcGRhdGVSZWZ1bmRSZXF1ZXN0GiAucGF5bWVudC52MS5VcGRhdGVSZWZ1bmRSZXNwb25zZSIAElMKDENhbmNlbFJlZnVuZBIfLnBheW1lbnQudjEuQ2FuY2VsUmVmdW5kUmVxdWVzdBogLnBheW1lbnQudjEuQ2FuY2VsUmVmdW5kUmVzcG9uc2UiAEKvAQoOY29tLnBheW1lbnQudjFCDFNlcnZpY2VQcm90b1ABWkZnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL3BheW1lbnQvdjE7cGF5bWVudHYxogIDUFhYqgIKUGF5bWVudC5WMcoCClBheW1lbnRcVjHiAhZQYXltZW50XFYxXEdQQk1ldGFkYXRh6gILUGF5bWVudDo6VjFiBnByb3RvMw", [file_payment_v1_payment, file_payment_v1_refund]);

/**
 * @generated from service payment.v1.PaymentService
 */
export const PaymentService: GenService<{
  /**
   * @generated from rpc payment.v1.PaymentService.GetPayment
   */
  getPayment: {
    methodKind: "unary";
    input: typeof GetPaymentRequestSchema;
    output: typeof GetPaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.ListPayments
   */
  listPayments: {
    methodKind: "unary";
    input: typeof ListPaymentsRequestSchema;
    output: typeof ListPaymentsResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CreatePayment
   */
  createPayment: {
    methodKind: "unary";
    input: typeof CreatePaymentRequestSchema;
    output: typeof CreatePaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.UpdatePayment
   */
  updatePayment: {
    methodKind: "unary";
    input: typeof UpdatePaymentRequestSchema;
    output: typeof UpdatePaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CancelPayment
   */
  cancelPayment: {
    methodKind: "unary";
    input: typeof CancelPaymentRequestSchema;
    output: typeof CancelPaymentResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.GetRefund
   */
  getRefund: {
    methodKind: "unary";
    input: typeof GetRefundRequestSchema;
    output: typeof GetRefundResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.ListRefunds
   */
  listRefunds: {
    methodKind: "unary";
    input: typeof ListRefundsRequestSchema;
    output: typeof ListRefundsResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CreateRefund
   */
  createRefund: {
    methodKind: "unary";
    input: typeof CreateRefundRequestSchema;
    output: typeof CreateRefundResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.UpdateRefund
   */
  updateRefund: {
    methodKind: "unary";
    input: typeof UpdateRefundRequestSchema;
    output: typeof UpdateRefundResponseSchema;
  },
  /**
   * @generated from rpc payment.v1.PaymentService.CancelRefund
   */
  cancelRefund: {
    methodKind: "unary";
    input: typeof CancelRefundRequestSchema;
    output: typeof CancelRefundResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_payment_v1_service, 0);

