// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file payment/v1/service.proto (package payment.v1, syntax proto3)
/* eslint-disable */

import { PaymentService } from "./service_pb";

/**
 * @generated from rpc payment.v1.PaymentService.GetPayment
 */
export const getPayment = PaymentService.method.getPayment;

/**
 * @generated from rpc payment.v1.PaymentService.ListPayments
 */
export const listPayments = PaymentService.method.listPayments;

/**
 * @generated from rpc payment.v1.PaymentService.CreatePayment
 */
export const createPayment = PaymentService.method.createPayment;

/**
 * @generated from rpc payment.v1.PaymentService.UpdatePayment
 */
export const updatePayment = PaymentService.method.updatePayment;

/**
 * @generated from rpc payment.v1.PaymentService.CancelPayment
 */
export const cancelPayment = PaymentService.method.cancelPayment;

/**
 * @generated from rpc payment.v1.PaymentService.GetRefund
 */
export const getRefund = PaymentService.method.getRefund;

/**
 * @generated from rpc payment.v1.PaymentService.ListRefunds
 */
export const listRefunds = PaymentService.method.listRefunds;

/**
 * @generated from rpc payment.v1.PaymentService.CreateRefund
 */
export const createRefund = PaymentService.method.createRefund;

/**
 * @generated from rpc payment.v1.PaymentService.UpdateRefund
 */
export const updateRefund = PaymentService.method.updateRefund;

/**
 * @generated from rpc payment.v1.PaymentService.CancelRefund
 */
export const cancelRefund = PaymentService.method.cancelRefund;
