// @generated by protoc-gen-es v2.2.3
// @generated from file account/v1/account.proto (package account.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file account/v1/account.proto.
 */
export declare const file_account_v1_account: GenFile;

/**
 * @generated from message account.v1.RegisterUserRequest
 */
export declare type RegisterUserRequest = Message<"account.v1.RegisterUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string phone = 3;
   */
  phone: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: account.v1.Gender gender = 5;
   */
  gender: Gender;

  /**
   * @generated from field: string full_name = 6;
   */
  fullName: string;
};

/**
 * Describes the message account.v1.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export declare const RegisterUserRequestSchema: GenMessage<RegisterUserRequest>;

/**
 * @generated from message account.v1.RegisterUserResponse
 */
export declare type RegisterUserResponse = Message<"account.v1.RegisterUserResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.RegisterUserResponse.
 * Use `create(RegisterUserResponseSchema)` to create a new message.
 */
export declare const RegisterUserResponseSchema: GenMessage<RegisterUserResponse>;

/**
 * @generated from message account.v1.RegisterAdminRequest
 */
export declare type RegisterAdminRequest = Message<"account.v1.RegisterAdminRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message account.v1.RegisterAdminRequest.
 * Use `create(RegisterAdminRequestSchema)` to create a new message.
 */
export declare const RegisterAdminRequestSchema: GenMessage<RegisterAdminRequest>;

/**
 * @generated from message account.v1.RegisterAdminResponse
 */
export declare type RegisterAdminResponse = Message<"account.v1.RegisterAdminResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.RegisterAdminResponse.
 * Use `create(RegisterAdminResponseSchema)` to create a new message.
 */
export declare const RegisterAdminResponseSchema: GenMessage<RegisterAdminResponse>;

/**
 * @generated from message account.v1.LoginUserRequest
 */
export declare type LoginUserRequest = Message<"account.v1.LoginUserRequest"> & {
  /**
   * @generated from field: optional string username = 1;
   */
  username?: string;

  /**
   * @generated from field: optional string email = 2;
   */
  email?: string;

  /**
   * @generated from field: optional string phone = 3;
   */
  phone?: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;
};

/**
 * Describes the message account.v1.LoginUserRequest.
 * Use `create(LoginUserRequestSchema)` to create a new message.
 */
export declare const LoginUserRequestSchema: GenMessage<LoginUserRequest>;

/**
 * @generated from message account.v1.LoginUserResponse
 */
export declare type LoginUserResponse = Message<"account.v1.LoginUserResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.LoginUserResponse.
 * Use `create(LoginUserResponseSchema)` to create a new message.
 */
export declare const LoginUserResponseSchema: GenMessage<LoginUserResponse>;

/**
 * @generated from message account.v1.LoginAdminRequest
 */
export declare type LoginAdminRequest = Message<"account.v1.LoginAdminRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message account.v1.LoginAdminRequest.
 * Use `create(LoginAdminRequestSchema)` to create a new message.
 */
export declare const LoginAdminRequestSchema: GenMessage<LoginAdminRequest>;

/**
 * @generated from message account.v1.LoginAdminResponse
 */
export declare type LoginAdminResponse = Message<"account.v1.LoginAdminResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.LoginAdminResponse.
 * Use `create(LoginAdminResponseSchema)` to create a new message.
 */
export declare const LoginAdminResponseSchema: GenMessage<LoginAdminResponse>;

/**
 * @generated from enum account.v1.Gender
 */
export enum Gender {
  /**
   * @generated from enum value: GENDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GENDER_MALE = 1;
   */
  MALE = 1,

  /**
   * @generated from enum value: GENDER_FEMALE = 2;
   */
  FEMALE = 2,

  /**
   * @generated from enum value: GENDER_OTHER = 3;
   */
  OTHER = 3,
}

/**
 * Describes the enum account.v1.Gender.
 */
export declare const GenderSchema: GenEnum<Gender>;

