// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file account/v1/account.proto (package account.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file account/v1/account.proto.
 */
export const file_account_v1_account: GenFile = /*@__PURE__*/
  fileDesc("ChhhY2NvdW50L3YxL2FjY291bnQucHJvdG8SCmFjY291bnQudjEiEAoOR2V0VXNlclJlcXVlc3QisAEKD0dldFVzZXJSZXNwb25zZRINCgVlbWFpbBgBIAEoCRINCgVwaG9uZRgCIAEoCRIQCgh1c2VybmFtZRgDIAEoCRIiCgZnZW5kZXIYBCABKA4yEi5hY2NvdW50LnYxLkdlbmRlchIRCglmdWxsX25hbWUYBSABKAkSHwoSZGVmYXVsdF9hZGRyZXNzX2lkGAYgASgDSACIAQFCFQoTX2RlZmF1bHRfYWRkcmVzc19pZCKOAQoTUmVnaXN0ZXJVc2VyUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRINCgVlbWFpbBgCIAEoCRINCgVwaG9uZRgDIAEoCRIQCghwYXNzd29yZBgEIAEoCRIiCgZnZW5kZXIYBSABKA4yEi5hY2NvdW50LnYxLkdlbmRlchIRCglmdWxsX25hbWUYBiABKAkiJQoUUmVnaXN0ZXJVc2VyUmVzcG9uc2USDQoFdG9rZW4YASABKAkiOgoUUmVnaXN0ZXJBZG1pblJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiJgoVUmVnaXN0ZXJBZG1pblJlc3BvbnNlEg0KBXRva2VuGAEgASgJIoQBChBMb2dpblVzZXJSZXF1ZXN0EhUKCHVzZXJuYW1lGAEgASgJSACIAQESEgoFZW1haWwYAiABKAlIAYgBARISCgVwaG9uZRgDIAEoCUgCiAEBEhAKCHBhc3N3b3JkGAQgASgJQgsKCV91c2VybmFtZUIICgZfZW1haWxCCAoGX3Bob25lIiIKEUxvZ2luVXNlclJlc3BvbnNlEg0KBXRva2VuGAEgASgJIjcKEUxvZ2luQWRtaW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIiMKEkxvZ2luQWRtaW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCSpWCgZHZW5kZXISFgoSR0VOREVSX1VOU1BFQ0lGSUVEEAASDwoLR0VOREVSX01BTEUQARIRCg1HRU5ERVJfRkVNQUxFEAISEAoMR0VOREVSX09USEVSEANCrwEKDmNvbS5hY2NvdW50LnYxQgxBY2NvdW50UHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9hY2NvdW50L3YxO2FjY291bnR2MaICA0FYWKoCCkFjY291bnQuVjHKAgpBY2NvdW50XFYx4gIWQWNjb3VudFxWMVxHUEJNZXRhZGF0YeoCC0FjY291bnQ6OlYxYgZwcm90bzM");

/**
 * @generated from message account.v1.GetUserRequest
 */
export type GetUserRequest = Message<"account.v1.GetUserRequest"> & {
};

/**
 * Describes the message account.v1.GetUserRequest.
 * Use `create(GetUserRequestSchema)` to create a new message.
 */
export const GetUserRequestSchema: GenMessage<GetUserRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 0);

/**
 * @generated from message account.v1.GetUserResponse
 */
export type GetUserResponse = Message<"account.v1.GetUserResponse"> & {
  /**
   * @generated from field: string email = 1;
   */
  email: string;

  /**
   * @generated from field: string phone = 2;
   */
  phone: string;

  /**
   * @generated from field: string username = 3;
   */
  username: string;

  /**
   * @generated from field: account.v1.Gender gender = 4;
   */
  gender: Gender;

  /**
   * @generated from field: string full_name = 5;
   */
  fullName: string;

  /**
   * @generated from field: optional int64 default_address_id = 6;
   */
  defaultAddressId?: bigint;
};

/**
 * Describes the message account.v1.GetUserResponse.
 * Use `create(GetUserResponseSchema)` to create a new message.
 */
export const GetUserResponseSchema: GenMessage<GetUserResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 1);

/**
 * @generated from message account.v1.RegisterUserRequest
 */
export type RegisterUserRequest = Message<"account.v1.RegisterUserRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string email = 2;
   */
  email: string;

  /**
   * @generated from field: string phone = 3;
   */
  phone: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;

  /**
   * @generated from field: account.v1.Gender gender = 5;
   */
  gender: Gender;

  /**
   * @generated from field: string full_name = 6;
   */
  fullName: string;
};

/**
 * Describes the message account.v1.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export const RegisterUserRequestSchema: GenMessage<RegisterUserRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 2);

/**
 * @generated from message account.v1.RegisterUserResponse
 */
export type RegisterUserResponse = Message<"account.v1.RegisterUserResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.RegisterUserResponse.
 * Use `create(RegisterUserResponseSchema)` to create a new message.
 */
export const RegisterUserResponseSchema: GenMessage<RegisterUserResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 3);

/**
 * @generated from message account.v1.RegisterAdminRequest
 */
export type RegisterAdminRequest = Message<"account.v1.RegisterAdminRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message account.v1.RegisterAdminRequest.
 * Use `create(RegisterAdminRequestSchema)` to create a new message.
 */
export const RegisterAdminRequestSchema: GenMessage<RegisterAdminRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 4);

/**
 * @generated from message account.v1.RegisterAdminResponse
 */
export type RegisterAdminResponse = Message<"account.v1.RegisterAdminResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.RegisterAdminResponse.
 * Use `create(RegisterAdminResponseSchema)` to create a new message.
 */
export const RegisterAdminResponseSchema: GenMessage<RegisterAdminResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 5);

/**
 * @generated from message account.v1.LoginUserRequest
 */
export type LoginUserRequest = Message<"account.v1.LoginUserRequest"> & {
  /**
   * @generated from field: optional string username = 1;
   */
  username?: string;

  /**
   * @generated from field: optional string email = 2;
   */
  email?: string;

  /**
   * @generated from field: optional string phone = 3;
   */
  phone?: string;

  /**
   * @generated from field: string password = 4;
   */
  password: string;
};

/**
 * Describes the message account.v1.LoginUserRequest.
 * Use `create(LoginUserRequestSchema)` to create a new message.
 */
export const LoginUserRequestSchema: GenMessage<LoginUserRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 6);

/**
 * @generated from message account.v1.LoginUserResponse
 */
export type LoginUserResponse = Message<"account.v1.LoginUserResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.LoginUserResponse.
 * Use `create(LoginUserResponseSchema)` to create a new message.
 */
export const LoginUserResponseSchema: GenMessage<LoginUserResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 7);

/**
 * @generated from message account.v1.LoginAdminRequest
 */
export type LoginAdminRequest = Message<"account.v1.LoginAdminRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message account.v1.LoginAdminRequest.
 * Use `create(LoginAdminRequestSchema)` to create a new message.
 */
export const LoginAdminRequestSchema: GenMessage<LoginAdminRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 8);

/**
 * @generated from message account.v1.LoginAdminResponse
 */
export type LoginAdminResponse = Message<"account.v1.LoginAdminResponse"> & {
  /**
   * @generated from field: string token = 1;
   */
  token: string;
};

/**
 * Describes the message account.v1.LoginAdminResponse.
 * Use `create(LoginAdminResponseSchema)` to create a new message.
 */
export const LoginAdminResponseSchema: GenMessage<LoginAdminResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_account, 9);

/**
 * @generated from enum account.v1.Gender
 */
export enum Gender {
  /**
   * @generated from enum value: GENDER_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GENDER_MALE = 1;
   */
  MALE = 1,

  /**
   * @generated from enum value: GENDER_FEMALE = 2;
   */
  FEMALE = 2,

  /**
   * @generated from enum value: GENDER_OTHER = 3;
   */
  OTHER = 3,
}

/**
 * Describes the enum account.v1.Gender.
 */
export const GenderSchema: GenEnum<Gender> = /*@__PURE__*/
  enumDesc(file_account_v1_account, 0);

