// @generated by protoc-gen-es v2.2.3
// @generated from file account/v1/account.proto (package account.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file account/v1/account.proto.
 */
export const file_account_v1_account = /*@__PURE__*/
  fileDesc("ChhhY2NvdW50L3YxL2FjY291bnQucHJvdG8SCmFjY291bnQudjEijgEKE1JlZ2lzdGVyVXNlclJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSDQoFZW1haWwYAiABKAkSDQoFcGhvbmUYAyABKAkSEAoIcGFzc3dvcmQYBCABKAkSIgoGZ2VuZGVyGAUgASgOMhIuYWNjb3VudC52MS5HZW5kZXISEQoJZnVsbF9uYW1lGAYgASgJIiUKFFJlZ2lzdGVyVXNlclJlc3BvbnNlEg0KBXRva2VuGAEgASgJIjoKFFJlZ2lzdGVyQWRtaW5SZXF1ZXN0EhAKCHVzZXJuYW1lGAEgASgJEhAKCHBhc3N3b3JkGAIgASgJIiYKFVJlZ2lzdGVyQWRtaW5SZXNwb25zZRINCgV0b2tlbhgBIAEoCSKEAQoQTG9naW5Vc2VyUmVxdWVzdBIVCgh1c2VybmFtZRgBIAEoCUgAiAEBEhIKBWVtYWlsGAIgASgJSAGIAQESEgoFcGhvbmUYAyABKAlIAogBARIQCghwYXNzd29yZBgEIAEoCUILCglfdXNlcm5hbWVCCAoGX2VtYWlsQggKBl9waG9uZSIiChFMb2dpblVzZXJSZXNwb25zZRINCgV0b2tlbhgBIAEoCSI3ChFMb2dpbkFkbWluUmVxdWVzdBIQCgh1c2VybmFtZRgBIAEoCRIQCghwYXNzd29yZBgCIAEoCSIjChJMb2dpbkFkbWluUmVzcG9uc2USDQoFdG9rZW4YASABKAkqVgoGR2VuZGVyEhYKEkdFTkRFUl9VTlNQRUNJRklFRBAAEg8KC0dFTkRFUl9NQUxFEAESEQoNR0VOREVSX0ZFTUFMRRACEhAKDEdFTkRFUl9PVEhFUhADQq8BCg5jb20uYWNjb3VudC52MUIMQWNjb3VudFByb3RvUAFaRmdpdGh1Yi5jb20vc2hvcG5leHVzL3Nob3BuZXh1cy1wcm90b2J1Zi1nZW4tZ28vcGIvYWNjb3VudC92MTthY2NvdW50djGiAgNBWFiqAgpBY2NvdW50LlYxygIKQWNjb3VudFxWMeICFkFjY291bnRcVjFcR1BCTWV0YWRhdGHqAgtBY2NvdW50OjpWMWIGcHJvdG8z");

/**
 * Describes the message account.v1.RegisterUserRequest.
 * Use `create(RegisterUserRequestSchema)` to create a new message.
 */
export const RegisterUserRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 0);

/**
 * Describes the message account.v1.RegisterUserResponse.
 * Use `create(RegisterUserResponseSchema)` to create a new message.
 */
export const RegisterUserResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 1);

/**
 * Describes the message account.v1.RegisterAdminRequest.
 * Use `create(RegisterAdminRequestSchema)` to create a new message.
 */
export const RegisterAdminRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 2);

/**
 * Describes the message account.v1.RegisterAdminResponse.
 * Use `create(RegisterAdminResponseSchema)` to create a new message.
 */
export const RegisterAdminResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 3);

/**
 * Describes the message account.v1.LoginUserRequest.
 * Use `create(LoginUserRequestSchema)` to create a new message.
 */
export const LoginUserRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 4);

/**
 * Describes the message account.v1.LoginUserResponse.
 * Use `create(LoginUserResponseSchema)` to create a new message.
 */
export const LoginUserResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 5);

/**
 * Describes the message account.v1.LoginAdminRequest.
 * Use `create(LoginAdminRequestSchema)` to create a new message.
 */
export const LoginAdminRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 6);

/**
 * Describes the message account.v1.LoginAdminResponse.
 * Use `create(LoginAdminResponseSchema)` to create a new message.
 */
export const LoginAdminResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_account, 7);

/**
 * Describes the enum account.v1.Gender.
 */
export const GenderSchema = /*@__PURE__*/
  enumDesc(file_account_v1_account, 0);

/**
 * @generated from enum account.v1.Gender
 */
export const Gender = /*@__PURE__*/
  tsEnum(GenderSchema);

