// @generated by protoc-gen-es v2.2.3
// @generated from file account/v1/cart.proto (package account.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_common_item_quantity } from "../../common/item_quantity_pb";

/**
 * Describes the file account/v1/cart.proto.
 */
export const file_account_v1_cart = /*@__PURE__*/
  fileDesc("ChVhY2NvdW50L3YxL2NhcnQucHJvdG8SCmFjY291bnQudjEiEAoOR2V0Q2FydFJlcXVlc3QiNgoPR2V0Q2FydFJlc3BvbnNlEiMKBWl0ZW1zGAEgAygLMhQuY29tbW9uLkl0ZW1RdWFudGl0eSI5ChJBZGRDYXJ0SXRlbVJlcXVlc3QSIwoFaXRlbXMYASADKAsyFC5jb21tb24uSXRlbVF1YW50aXR5IjoKE0FkZENhcnRJdGVtUmVzcG9uc2USIwoFaXRlbXMYASADKAsyFC5jb21tb24uSXRlbVF1YW50aXR5IjwKFVVwZGF0ZUNhcnRJdGVtUmVxdWVzdBIjCgVpdGVtcxgBIAMoCzIULmNvbW1vbi5JdGVtUXVhbnRpdHkiGAoWVXBkYXRlQ2FydEl0ZW1SZXNwb25zZUKsAQoOY29tLmFjY291bnQudjFCCUNhcnRQcm90b1ABWkZnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL2FjY291bnQvdjE7YWNjb3VudHYxogIDQVhYqgIKQWNjb3VudC5WMcoCCkFjY291bnRcVjHiAhZBY2NvdW50XFYxXEdQQk1ldGFkYXRh6gILQWNjb3VudDo6VjFiBnByb3RvMw", [file_common_item_quantity]);

/**
 * Describes the message account.v1.GetCartRequest.
 * Use `create(GetCartRequestSchema)` to create a new message.
 */
export const GetCartRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 0);

/**
 * Describes the message account.v1.GetCartResponse.
 * Use `create(GetCartResponseSchema)` to create a new message.
 */
export const GetCartResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 1);

/**
 * Describes the message account.v1.AddCartItemRequest.
 * Use `create(AddCartItemRequestSchema)` to create a new message.
 */
export const AddCartItemRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 2);

/**
 * Describes the message account.v1.AddCartItemResponse.
 * Use `create(AddCartItemResponseSchema)` to create a new message.
 */
export const AddCartItemResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 3);

/**
 * Describes the message account.v1.UpdateCartItemRequest.
 * Use `create(UpdateCartItemRequestSchema)` to create a new message.
 */
export const UpdateCartItemRequestSchema = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 4);

/**
 * Describes the message account.v1.UpdateCartItemResponse.
 * Use `create(UpdateCartItemResponseSchema)` to create a new message.
 */
export const UpdateCartItemResponseSchema = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 5);

