// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file account/v1/cart.proto (package account.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { ItemQuantityInt64 } from "../../common/item_quantity_pb";
import { file_common_item_quantity } from "../../common/item_quantity_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file account/v1/cart.proto.
 */
export const file_account_v1_cart: GenFile = /*@__PURE__*/
  fileDesc("ChVhY2NvdW50L3YxL2NhcnQucHJvdG8SCmFjY291bnQudjEiEAoOR2V0Q2FydFJlcXVlc3QiOwoPR2V0Q2FydFJlc3BvbnNlEigKBWl0ZW1zGAEgAygLMhkuY29tbW9uLkl0ZW1RdWFudGl0eUludDY0Ij4KEkFkZENhcnRJdGVtUmVxdWVzdBIoCgVpdGVtcxgBIAMoCzIZLmNvbW1vbi5JdGVtUXVhbnRpdHlJbnQ2NCI/ChNBZGRDYXJ0SXRlbVJlc3BvbnNlEigKBWl0ZW1zGAEgAygLMhkuY29tbW9uLkl0ZW1RdWFudGl0eUludDY0IkEKFVVwZGF0ZUNhcnRJdGVtUmVxdWVzdBIoCgVpdGVtcxgBIAMoCzIZLmNvbW1vbi5JdGVtUXVhbnRpdHlJbnQ2NCIYChZVcGRhdGVDYXJ0SXRlbVJlc3BvbnNlIhIKEENsZWFyQ2FydFJlcXVlc3QiEwoRQ2xlYXJDYXJ0UmVzcG9uc2VCrAEKDmNvbS5hY2NvdW50LnYxQglDYXJ0UHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9hY2NvdW50L3YxO2FjY291bnR2MaICA0FYWKoCCkFjY291bnQuVjHKAgpBY2NvdW50XFYx4gIWQWNjb3VudFxWMVxHUEJNZXRhZGF0YeoCC0FjY291bnQ6OlYxYgZwcm90bzM", [file_common_item_quantity]);

/**
 * @generated from message account.v1.GetCartRequest
 */
export type GetCartRequest = Message<"account.v1.GetCartRequest"> & {
};

/**
 * Describes the message account.v1.GetCartRequest.
 * Use `create(GetCartRequestSchema)` to create a new message.
 */
export const GetCartRequestSchema: GenMessage<GetCartRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 0);

/**
 * @generated from message account.v1.GetCartResponse
 */
export type GetCartResponse = Message<"account.v1.GetCartResponse"> & {
  /**
   * @generated from field: repeated common.ItemQuantityInt64 items = 1;
   */
  items: ItemQuantityInt64[];
};

/**
 * Describes the message account.v1.GetCartResponse.
 * Use `create(GetCartResponseSchema)` to create a new message.
 */
export const GetCartResponseSchema: GenMessage<GetCartResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 1);

/**
 * @generated from message account.v1.AddCartItemRequest
 */
export type AddCartItemRequest = Message<"account.v1.AddCartItemRequest"> & {
  /**
   * @generated from field: repeated common.ItemQuantityInt64 items = 1;
   */
  items: ItemQuantityInt64[];
};

/**
 * Describes the message account.v1.AddCartItemRequest.
 * Use `create(AddCartItemRequestSchema)` to create a new message.
 */
export const AddCartItemRequestSchema: GenMessage<AddCartItemRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 2);

/**
 * @generated from message account.v1.AddCartItemResponse
 */
export type AddCartItemResponse = Message<"account.v1.AddCartItemResponse"> & {
  /**
   * @generated from field: repeated common.ItemQuantityInt64 items = 1;
   */
  items: ItemQuantityInt64[];
};

/**
 * Describes the message account.v1.AddCartItemResponse.
 * Use `create(AddCartItemResponseSchema)` to create a new message.
 */
export const AddCartItemResponseSchema: GenMessage<AddCartItemResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 3);

/**
 * @generated from message account.v1.UpdateCartItemRequest
 */
export type UpdateCartItemRequest = Message<"account.v1.UpdateCartItemRequest"> & {
  /**
   * @generated from field: repeated common.ItemQuantityInt64 items = 1;
   */
  items: ItemQuantityInt64[];
};

/**
 * Describes the message account.v1.UpdateCartItemRequest.
 * Use `create(UpdateCartItemRequestSchema)` to create a new message.
 */
export const UpdateCartItemRequestSchema: GenMessage<UpdateCartItemRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 4);

/**
 * @generated from message account.v1.UpdateCartItemResponse
 */
export type UpdateCartItemResponse = Message<"account.v1.UpdateCartItemResponse"> & {
};

/**
 * Describes the message account.v1.UpdateCartItemResponse.
 * Use `create(UpdateCartItemResponseSchema)` to create a new message.
 */
export const UpdateCartItemResponseSchema: GenMessage<UpdateCartItemResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 5);

/**
 * @generated from message account.v1.ClearCartRequest
 */
export type ClearCartRequest = Message<"account.v1.ClearCartRequest"> & {
};

/**
 * Describes the message account.v1.ClearCartRequest.
 * Use `create(ClearCartRequestSchema)` to create a new message.
 */
export const ClearCartRequestSchema: GenMessage<ClearCartRequest> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 6);

/**
 * @generated from message account.v1.ClearCartResponse
 */
export type ClearCartResponse = Message<"account.v1.ClearCartResponse"> & {
};

/**
 * Describes the message account.v1.ClearCartResponse.
 * Use `create(ClearCartResponseSchema)` to create a new message.
 */
export const ClearCartResponseSchema: GenMessage<ClearCartResponse> = /*@__PURE__*/
  messageDesc(file_account_v1_cart, 7);

