// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file account/v1/service.proto (package account.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { LoginAdminRequestSchema, LoginAdminResponseSchema, LoginUserRequestSchema, LoginUserResponseSchema, RegisterAdminRequestSchema, RegisterAdminResponseSchema, RegisterUserRequestSchema, RegisterUserResponseSchema } from "./account_pb";
import { file_account_v1_account } from "./account_pb";
import type { AddCartItemRequestSchema, AddCartItemResponseSchema, ClearCartRequestSchema, ClearCartResponseSchema, GetCartRequestSchema, GetCartResponseSchema, UpdateCartItemRequestSchema, UpdateCartItemResponseSchema } from "./cart_pb";
import { file_account_v1_cart } from "./cart_pb";

/**
 * Describes the file account/v1/service.proto.
 */
export const file_account_v1_service: GenFile = /*@__PURE__*/
  fileDesc("ChhhY2NvdW50L3YxL3NlcnZpY2UucHJvdG8SCmFjY291bnQudjEymgUKDkFjY291bnRTZXJ2aWNlEkoKCUxvZ2luVXNlchIcLmFjY291bnQudjEuTG9naW5Vc2VyUmVxdWVzdBodLmFjY291bnQudjEuTG9naW5Vc2VyUmVzcG9uc2UiABJNCgpMb2dpbkFkbWluEh0uYWNjb3VudC52MS5Mb2dpbkFkbWluUmVxdWVzdBoeLmFjY291bnQudjEuTG9naW5BZG1pblJlc3BvbnNlIgASUwoMUmVnaXN0ZXJVc2VyEh8uYWNjb3VudC52MS5SZWdpc3RlclVzZXJSZXF1ZXN0GiAuYWNjb3VudC52MS5SZWdpc3RlclVzZXJSZXNwb25zZSIAElYKDVJlZ2lzdGVyQWRtaW4SIC5hY2NvdW50LnYxLlJlZ2lzdGVyQWRtaW5SZXF1ZXN0GiEuYWNjb3VudC52MS5SZWdpc3RlckFkbWluUmVzcG9uc2UiABJHCgdHZXRDYXJ0EhouYWNjb3VudC52MS5HZXRDYXJ0UmVxdWVzdBobLmFjY291bnQudjEuR2V0Q2FydFJlc3BvbnNlIgOQAgESUAoLQWRkQ2FydEl0ZW0SHi5hY2NvdW50LnYxLkFkZENhcnRJdGVtUmVxdWVzdBofLmFjY291bnQudjEuQWRkQ2FydEl0ZW1SZXNwb25zZSIAElkKDlVwZGF0ZUNhcnRJdGVtEiEuYWNjb3VudC52MS5VcGRhdGVDYXJ0SXRlbVJlcXVlc3QaIi5hY2NvdW50LnYxLlVwZGF0ZUNhcnRJdGVtUmVzcG9uc2UiABJKCglDbGVhckNhcnQSHC5hY2NvdW50LnYxLkNsZWFyQ2FydFJlcXVlc3QaHS5hY2NvdW50LnYxLkNsZWFyQ2FydFJlc3BvbnNlIgBCrwEKDmNvbS5hY2NvdW50LnYxQgxTZXJ2aWNlUHJvdG9QAVpGZ2l0aHViLmNvbS9zaG9wbmV4dXMvc2hvcG5leHVzLXByb3RvYnVmLWdlbi1nby9wYi9hY2NvdW50L3YxO2FjY291bnR2MaICA0FYWKoCCkFjY291bnQuVjHKAgpBY2NvdW50XFYx4gIWQWNjb3VudFxWMVxHUEJNZXRhZGF0YeoCC0FjY291bnQ6OlYxYgZwcm90bzM", [file_account_v1_account, file_account_v1_cart]);

/**
 * @generated from service account.v1.AccountService
 */
export const AccountService: GenService<{
  /**
   * Login, register
   *
   * @generated from rpc account.v1.AccountService.LoginUser
   */
  loginUser: {
    methodKind: "unary";
    input: typeof LoginUserRequestSchema;
    output: typeof LoginUserResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.LoginAdmin
   */
  loginAdmin: {
    methodKind: "unary";
    input: typeof LoginAdminRequestSchema;
    output: typeof LoginAdminResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.RegisterUser
   */
  registerUser: {
    methodKind: "unary";
    input: typeof RegisterUserRequestSchema;
    output: typeof RegisterUserResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.RegisterAdmin
   */
  registerAdmin: {
    methodKind: "unary";
    input: typeof RegisterAdminRequestSchema;
    output: typeof RegisterAdminResponseSchema;
  },
  /**
   * Cart
   *
   * @generated from rpc account.v1.AccountService.GetCart
   */
  getCart: {
    methodKind: "unary";
    input: typeof GetCartRequestSchema;
    output: typeof GetCartResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.AddCartItem
   */
  addCartItem: {
    methodKind: "unary";
    input: typeof AddCartItemRequestSchema;
    output: typeof AddCartItemResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.UpdateCartItem
   */
  updateCartItem: {
    methodKind: "unary";
    input: typeof UpdateCartItemRequestSchema;
    output: typeof UpdateCartItemResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.ClearCart
   */
  clearCart: {
    methodKind: "unary";
    input: typeof ClearCartRequestSchema;
    output: typeof ClearCartResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_account_v1_service, 0);

