// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file account/v1/service.proto (package account.v1, syntax proto3)
/* eslint-disable */

import { AccountService } from "./service_pb";

/**
 * @generated from rpc account.v1.AccountService.GetUser
 */
export const getUser = AccountService.method.getUser;

/**
 * @generated from rpc account.v1.AccountService.GetAdmin
 */
export const getAdmin = AccountService.method.getAdmin;

/**
 * @generated from rpc account.v1.AccountService.GetUserPublic
 */
export const getUserPublic = AccountService.method.getUserPublic;

/**
 * @generated from rpc account.v1.AccountService.UpdateAccount
 */
export const updateAccount = AccountService.method.updateAccount;

/**
 * @generated from rpc account.v1.AccountService.UpdateUser
 */
export const updateUser = AccountService.method.updateUser;

/**
 * Login, register
 *
 * @generated from rpc account.v1.AccountService.LoginUser
 */
export const loginUser = AccountService.method.loginUser;

/**
 * @generated from rpc account.v1.AccountService.LoginAdmin
 */
export const loginAdmin = AccountService.method.loginAdmin;

/**
 * @generated from rpc account.v1.AccountService.RegisterUser
 */
export const registerUser = AccountService.method.registerUser;

/**
 * @generated from rpc account.v1.AccountService.RegisterAdmin
 */
export const registerAdmin = AccountService.method.registerAdmin;

/**
 * Cart
 *
 * @generated from rpc account.v1.AccountService.GetCart
 */
export const getCart = AccountService.method.getCart;

/**
 * @generated from rpc account.v1.AccountService.AddCartItem
 */
export const addCartItem = AccountService.method.addCartItem;

/**
 * @generated from rpc account.v1.AccountService.UpdateCartItem
 */
export const updateCartItem = AccountService.method.updateCartItem;

/**
 * @generated from rpc account.v1.AccountService.ClearCart
 */
export const clearCart = AccountService.method.clearCart;

/**
 * Address
 *
 * @generated from rpc account.v1.AccountService.GetAddress
 */
export const getAddress = AccountService.method.getAddress;

/**
 * @generated from rpc account.v1.AccountService.ListAddresses
 */
export const listAddresses = AccountService.method.listAddresses;

/**
 * @generated from rpc account.v1.AccountService.CreateAddress
 */
export const createAddress = AccountService.method.createAddress;

/**
 * @generated from rpc account.v1.AccountService.UpdateAddress
 */
export const updateAddress = AccountService.method.updateAddress;

/**
 * @generated from rpc account.v1.AccountService.DeleteAddress
 */
export const deleteAddress = AccountService.method.deleteAddress;
