// @generated by protoc-gen-es v2.2.3
// @generated from file account/v1/service.proto (package account.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenService } from "@bufbuild/protobuf/codegenv1";
import type { LoginAdminRequestSchema, LoginAdminResponseSchema, LoginUserRequestSchema, LoginUserResponseSchema, RegisterAdminRequestSchema, RegisterAdminResponseSchema, RegisterUserRequestSchema, RegisterUserResponseSchema } from "./account_pb";
import type { AddCartItemRequestSchema, AddCartItemResponseSchema, ClearCartRequestSchema, ClearCartResponseSchema, GetCartRequestSchema, GetCartResponseSchema, UpdateCartItemRequestSchema, UpdateCartItemResponseSchema } from "./cart_pb";

/**
 * Describes the file account/v1/service.proto.
 */
export declare const file_account_v1_service: GenFile;

/**
 * @generated from service account.v1.AccountService
 */
export declare const AccountService: GenService<{
  /**
   * Login, register
   *
   * @generated from rpc account.v1.AccountService.LoginUser
   */
  loginUser: {
    methodKind: "unary";
    input: typeof LoginUserRequestSchema;
    output: typeof LoginUserResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.LoginAdmin
   */
  loginAdmin: {
    methodKind: "unary";
    input: typeof LoginAdminRequestSchema;
    output: typeof LoginAdminResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.RegisterUser
   */
  registerUser: {
    methodKind: "unary";
    input: typeof RegisterUserRequestSchema;
    output: typeof RegisterUserResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.RegisterAdmin
   */
  registerAdmin: {
    methodKind: "unary";
    input: typeof RegisterAdminRequestSchema;
    output: typeof RegisterAdminResponseSchema;
  },
  /**
   * Cart
   *
   * @generated from rpc account.v1.AccountService.GetCart
   */
  getCart: {
    methodKind: "unary";
    input: typeof GetCartRequestSchema;
    output: typeof GetCartResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.AddCartItem
   */
  addCartItem: {
    methodKind: "unary";
    input: typeof AddCartItemRequestSchema;
    output: typeof AddCartItemResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.UpdateCartItem
   */
  updateCartItem: {
    methodKind: "unary";
    input: typeof UpdateCartItemRequestSchema;
    output: typeof UpdateCartItemResponseSchema;
  },
  /**
   * @generated from rpc account.v1.AccountService.ClearCart
   */
  clearCart: {
    methodKind: "unary";
    input: typeof ClearCartRequestSchema;
    output: typeof ClearCartResponseSchema;
  },
}>;

