// @generated by protoc-gen-connect-query v2.0.1 with parameter "target=ts"
// @generated from file account/v1/service.proto (package account.v1, syntax proto3)
/* eslint-disable */

import { AccountService } from "./service_pb";

/**
 * Login, register
 *
 * @generated from rpc account.v1.AccountService.LoginUser
 */
export const loginUser = AccountService.method.loginUser;

/**
 * @generated from rpc account.v1.AccountService.LoginAdmin
 */
export const loginAdmin = AccountService.method.loginAdmin;

/**
 * @generated from rpc account.v1.AccountService.RegisterUser
 */
export const registerUser = AccountService.method.registerUser;

/**
 * @generated from rpc account.v1.AccountService.RegisterAdmin
 */
export const registerAdmin = AccountService.method.registerAdmin;

/**
 * Cart
 *
 * @generated from rpc account.v1.AccountService.GetCart
 */
export const getCart = AccountService.method.getCart;

/**
 * @generated from rpc account.v1.AccountService.AddCartItem
 */
export const addCartItem = AccountService.method.addCartItem;

/**
 * @generated from rpc account.v1.AccountService.UpdateCartItem
 */
export const updateCartItem = AccountService.method.updateCartItem;

/**
 * @generated from rpc account.v1.AccountService.ClearCart
 */
export const clearCart = AccountService.method.clearCart;
