// @generated by protoc-gen-es v2.2.3
// @generated from file common/item_quantity.proto (package common, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/item_quantity.proto.
 */
export const file_common_item_quantity = /*@__PURE__*/
  fileDesc("Chpjb21tb24vaXRlbV9xdWFudGl0eS5wcm90bxIGY29tbW9uIjEKDEl0ZW1RdWFudGl0eRIPCgdpdGVtX2lkGAEgASgDEhAKCHF1YW50aXR5GAIgASgDQpEBCgpjb20uY29tbW9uQhFJdGVtUXVhbnRpdHlQcm90b1ABWjhnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL2NvbW1vbqICA0NYWKoCBkNvbW1vbsoCBkNvbW1vbuICEkNvbW1vblxHUEJNZXRhZGF0YeoCBkNvbW1vbmIGcHJvdG8z");

/**
 * Describes the message common.ItemQuantity.
 * Use `create(ItemQuantitySchema)` to create a new message.
 */
export const ItemQuantitySchema = /*@__PURE__*/
  messageDesc(file_common_item_quantity, 0);

