// @generated by protoc-gen-es v2.2.3
// @generated from file common/item_quantity.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/item_quantity.proto.
 */
export declare const file_common_item_quantity: GenFile;

/**
 * @generated from message common.ItemQuantity
 */
export declare type ItemQuantity = Message<"common.ItemQuantity"> & {
  /**
   * @generated from field: int64 item_id = 1;
   */
  itemId: bigint;

  /**
   * @generated from field: int64 quantity = 2;
   */
  quantity: bigint;
};

/**
 * Describes the message common.ItemQuantity.
 * Use `create(ItemQuantitySchema)` to create a new message.
 */
export declare const ItemQuantitySchema: GenMessage<ItemQuantity>;

