// @generated by protoc-gen-es v2.2.3
// @generated from file common/pagination.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/pagination.proto.
 */
export declare const file_common_pagination: GenFile;

/**
 * @generated from message common.PaginationRequest
 */
export declare type PaginationRequest = Message<"common.PaginationRequest"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: optional string cursor = 3;
   */
  cursor?: string;
};

/**
 * Describes the message common.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export declare const PaginationRequestSchema: GenMessage<PaginationRequest>;

/**
 * @generated from message common.PaginationResponse
 */
export declare type PaginationResponse = Message<"common.PaginationResponse"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: int64 total = 3;
   */
  total: bigint;

  /**
   * @generated from field: optional int32 next_page = 4;
   */
  nextPage?: number;

  /**
   * @generated from field: optional string next_cursor = 5;
   */
  nextCursor?: string;
};

/**
 * Describes the message common.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export declare const PaginationResponseSchema: GenMessage<PaginationResponse>;

