// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file common/pagination.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/pagination.proto.
 */
export const file_common_pagination: GenFile = /*@__PURE__*/
  fileDesc("Chdjb21tb24vcGFnaW5hdGlvbi5wcm90bxIGY29tbW9uIlAKEVBhZ2luYXRpb25SZXF1ZXN0EgwKBHBhZ2UYASABKAUSDQoFbGltaXQYAiABKAUSEwoGY3Vyc29yGAMgASgJSACIAQFCCQoHX2N1cnNvciKQAQoSUGFnaW5hdGlvblJlc3BvbnNlEgwKBHBhZ2UYASABKAUSDQoFbGltaXQYAiABKAUSDQoFdG90YWwYAyABKA0SFgoJbmV4dF9wYWdlGAQgASgFSACIAQESGAoLbmV4dF9jdXJzb3IYBSABKAlIAYgBAUIMCgpfbmV4dF9wYWdlQg4KDF9uZXh0X2N1cnNvckKPAQoKY29tLmNvbW1vbkIPUGFnaW5hdGlvblByb3RvUAFaOGdpdGh1Yi5jb20vc2hvcG5leHVzL3Nob3BuZXh1cy1wcm90b2J1Zi1nZW4tZ28vcGIvY29tbW9uogIDQ1hYqgIGQ29tbW9uygIGQ29tbW9u4gISQ29tbW9uXEdQQk1ldGFkYXRh6gIGQ29tbW9uYgZwcm90bzM");

/**
 * @generated from message common.PaginationRequest
 */
export type PaginationRequest = Message<"common.PaginationRequest"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: optional string cursor = 3;
   */
  cursor?: string;
};

/**
 * Describes the message common.PaginationRequest.
 * Use `create(PaginationRequestSchema)` to create a new message.
 */
export const PaginationRequestSchema: GenMessage<PaginationRequest> = /*@__PURE__*/
  messageDesc(file_common_pagination, 0);

/**
 * @generated from message common.PaginationResponse
 */
export type PaginationResponse = Message<"common.PaginationResponse"> & {
  /**
   * @generated from field: int32 page = 1;
   */
  page: number;

  /**
   * @generated from field: int32 limit = 2;
   */
  limit: number;

  /**
   * @generated from field: uint32 total = 3;
   */
  total: number;

  /**
   * @generated from field: optional int32 next_page = 4;
   */
  nextPage?: number;

  /**
   * @generated from field: optional string next_cursor = 5;
   */
  nextCursor?: string;
};

/**
 * Describes the message common.PaginationResponse.
 * Use `create(PaginationResponseSchema)` to create a new message.
 */
export const PaginationResponseSchema: GenMessage<PaginationResponse> = /*@__PURE__*/
  messageDesc(file_common_pagination, 1);

