// @generated by protoc-gen-es v2.2.3
// @generated from file common/status.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/status.proto.
 */
export declare const file_common_status: GenFile;

/**
 * @generated from enum common.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: STATUS_SUCCESS = 2;
   */
  SUCCESS = 2,

  /**
   * @generated from enum value: STATUS_CANCELLED = 3;
   */
  CANCELLED = 3,

  /**
   * @generated from enum value: STATUS_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum common.Status.
 */
export declare const StatusSchema: GenEnum<Status>;

