// @generated by protoc-gen-es v2.2.3
// @generated from file common/status.proto (package common, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/status.proto.
 */
export const file_common_status = /*@__PURE__*/
  fileDesc("ChNjb21tb24vc3RhdHVzLnByb3RvEgZjb21tb24qcQoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEhIKDlNUQVRVU19QRU5ESU5HEAESEgoOU1RBVFVTX1NVQ0NFU1MQAhIUChBTVEFUVVNfQ0FOQ0VMTEVEEAMSEQoNU1RBVFVTX0ZBSUxFRBAEQosBCgpjb20uY29tbW9uQgtTdGF0dXNQcm90b1ABWjhnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL2NvbW1vbqICA0NYWKoCBkNvbW1vbsoCBkNvbW1vbuICEkNvbW1vblxHUEJNZXRhZGF0YeoCBkNvbW1vbmIGcHJvdG8z");

/**
 * Describes the enum common.Status.
 */
export const StatusSchema = /*@__PURE__*/
  enumDesc(file_common_status, 0);

/**
 * @generated from enum common.Status
 */
export const Status = /*@__PURE__*/
  tsEnum(StatusSchema);

