// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file common/status.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/status.proto.
 */
export const file_common_status: GenFile = /*@__PURE__*/
  fileDesc("ChNjb21tb24vc3RhdHVzLnByb3RvEgZjb21tb24qcAoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEhIKDlNUQVRVU19QRU5ESU5HEAESEgoOU1RBVFVTX1NVQ0NFU1MQAhITCg9TVEFUVVNfQ0FOQ0VMRUQQAxIRCg1TVEFUVVNfRkFJTEVEEARCiwEKCmNvbS5jb21tb25CC1N0YXR1c1Byb3RvUAFaOGdpdGh1Yi5jb20vc2hvcG5leHVzL3Nob3BuZXh1cy1wcm90b2J1Zi1nZW4tZ28vcGIvY29tbW9uogIDQ1hYqgIGQ29tbW9uygIGQ29tbW9u4gISQ29tbW9uXEdQQk1ldGFkYXRh6gIGQ29tbW9uYgZwcm90bzM");

/**
 * @generated from enum common.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: STATUS_SUCCESS = 2;
   */
  SUCCESS = 2,

  /**
   * @generated from enum value: STATUS_CANCELED = 3;
   */
  CANCELED = 3,

  /**
   * @generated from enum value: STATUS_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum common.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_common_status, 0);

