// @generated by protoc-gen-es v2.2.3 with parameter "target=ts"
// @generated from file common/status.proto (package common, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile } from "@bufbuild/protobuf/codegenv1";
import { enumDesc, fileDesc } from "@bufbuild/protobuf/codegenv1";

/**
 * Describes the file common/status.proto.
 */
export const file_common_status: GenFile = /*@__PURE__*/
  fileDesc("ChNjb21tb24vc3RhdHVzLnByb3RvEgZjb21tb24qcQoGU3RhdHVzEhYKElNUQVRVU19VTlNQRUNJRklFRBAAEhIKDlNUQVRVU19QRU5ESU5HEAESEgoOU1RBVFVTX1NVQ0NFU1MQAhIUChBTVEFUVVNfQ0FOQ0VMTEVEEAMSEQoNU1RBVFVTX0ZBSUxFRBAEQosBCgpjb20uY29tbW9uQgtTdGF0dXNQcm90b1ABWjhnaXRodWIuY29tL3Nob3BuZXh1cy9zaG9wbmV4dXMtcHJvdG9idWYtZ2VuLWdvL3BiL2NvbW1vbqICA0NYWKoCBkNvbW1vbsoCBkNvbW1vbuICEkNvbW1vblxHUEJNZXRhZGF0YeoCBkNvbW1vbmIGcHJvdG8z");

/**
 * @generated from enum common.Status
 */
export enum Status {
  /**
   * @generated from enum value: STATUS_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: STATUS_PENDING = 1;
   */
  PENDING = 1,

  /**
   * @generated from enum value: STATUS_SUCCESS = 2;
   */
  SUCCESS = 2,

  /**
   * @generated from enum value: STATUS_CANCELLED = 3;
   */
  CANCELLED = 3,

  /**
   * @generated from enum value: STATUS_FAILED = 4;
   */
  FAILED = 4,
}

/**
 * Describes the enum common.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_common_status, 0);

